### ISSUE TITLE
Datei Auswahlfenster öffnet sich endlos

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#1]
Habe unter Infos auf das Icon für Datei Hochladen geklickt. Dann öffnet sich das Datei Auswahlfenster. Die entsprechende Datei habe ich damit ausgewählt und hochgeladen. Sofort danach öffnet sich wieder das Datei Auswahlfenster. Jedes mal wenn ich dann auf abbrechen klicke kommt das Fenster wieder. Durch das Schließen des Egde Browsers mit der Version 38 konnte ich das permanente Öffnen des Fensters umgehen. Den angezeigten Link der Datei kann ich nun anklicken, es kann die Datei jedoch nicht geöffnet werden. Ich nehme mal an das keine Datei hochgeladen wurde, obwohl der Link zur Datei angezeigt wird. Die Projekt Bezeichnung ist qVrQc.

**Comment by tim-antkowiak** [comment]
Hallo Mario,
danke für die Meldung! 
Das ist leider ein bekannter Bug im Edge Browser: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8282613/
Ich arbeite momentan an einem Workaround. Kannst du in der Zwischenzeit auf einen anderen Browser wie Chrome oder Firefox ausweichen?

Liebe Grüße
Tim

**Comment by schillermann** [comment]
Klar. Unbedarfte Benutzer werden da nicht mehr rauskommen. Kann man beim Aufruf der Funktion nicht eine Meldung raus schmeißen das die Funktion im Edge Browser wegen eines Bugs zur Zeit deaktiviert ist. Oder das zur Zeit diese Funktion im Edge Browser nicht unterstützt wird.
