### ISSUE TITLE
Schichten Vorlage - Langer Team Name bricht nicht um

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#10]
Der Team Name wird im Fenster unter Schichten Vorlage unter Teams über den Fensterrand hinaus geschrieben. Hier fehlt ein Zeilenumbruch bei längeren Team Namen.

**Comment by schillermann** [comment]
In der Schichten Ansicht werden die Team Namen auch nicht, bei zu langen Namen, umgebrochen.

**Comment by 51773ELLIS** [comment]
Danke, das ist nun behoben und wird in der nächsten Aktualisierung sein.

**Comment by MarvinZeising** [comment]
Reopening this since I now have a bug with my profile menu.

![ohne titel 2](https://cloud.githubusercontent.com/assets/12305625/21636688/eb54a092-d263-11e6-886a-08b6c015476d.png)

**Comment by 51773ELLIS** [comment]
Thanks for bringing to my attention, I have now isolated the fix to the areas required.
