### ISSUE TITLE
Fehler- TL kann nicht absagen

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#100]
Ein TL kann eine Schicht nicht verlassen. 
Es kommt der Hinweis " das Team wir gelöscht", oder so ähnlich. 
Das habe ich dann angeklickt, dann ist die Schicht unterbelegt, aber der TL steht immer nicht drin.
Morgen 03.02. um  12:00-14:00

**Comment by alisander2** [comment]
Ergänzung:

Heute morgen haben mich auch zwei TL angeschrieben,sie können sich auch nicht austragen. 
Wenn sie die Bewerbung zurückziehen wollen geht es nicht. Kommt eine Error Meldung.
Ich muss ihn an ablehnen, er bleibt im System aber stehen, bis er dann die Bewerbung zurücknimmt.

Bitte schnell lösen!

**Comment by tim-antkowiak** [comment]
Jetzt sollte es erstmal wieder funktionieren. Die Änderung geht mit dem nächsten Release live.
