### ISSUE TITLE
Fehlermeldung- Import von csv

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#103]
1. beim importieren werden teilweise bestehende Accounts nicht erkannt und es werden neue User angelegt obwohl die Mailadresse bekannt sind. 
2. sind Leerzeichen im Textfeld der email werden diese nicht von der csv-Import gelesen.

**Comment by kepano75** [comment]
3. Probleme mit Ä,Ö,Ü

**Comment by tim-antkowiak** [comment]
2. Ist behoben und geht mit dem nächsten Release live.

Zu 1. kann ich nur vermuten, dass es entweder mit 2. zusammenhängt oder die E-Mail Adressen nicht 100% mit den hinterlegten Adressen überein stimmen. Zum Beispiel hat Google seine Adressen vor einiger Zeit von @googlemail.com auf @gmail.com geändert. Wenn in der Datenbank noch die @googlemail.com hinterlegt ist und in deiner CSV-Datei die @gmail.com wird keine Übereinstimmung gefunden.
Wenn es doppelte Accounts gibt, dann schreib uns am besten eine E-Mail mit den User-Daten, dann fügen wir die Accounts manuell zusammen.

3. Hat zu tun mit der Kodierung der CSV-Datei. Leider versteht unser System nur UTF-8, das heißt, dass die Datei als UTF-8 abgespeichert werden muss, damit alles korrekt gelesen werden kann. Hier sind 2 Möglichkeiten:

- Datei mit Notepad++ öffnen -> Kodierung -> Konvertiere zu UTF-8 -> Speichern
- Datei mit Excel öffnen -> Speichern unter -> Dateityp -> "Unicode Text (*.txt)" und dann wieder in .csv umbenennen

Bei Fragen kannst du dich natürlich gerne an uns wenden.
