### ISSUE TITLE
Fehler - Schicht wird nicht automatisch wieder geöffnet

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#107]
Vielleicht ist es auch ein Anwenderfehler.
Wir haben als Vorgabe min. 3, bis zu vier VK pro Schicht und es steht auf "sofort zusagen".
Wenn sich jetzt vier VK angemeldet haben, dann wird die Schicht geschlossen.
Muss jetzt ein VK seine Bewerbung zurückziehen, dann bleibt die Schicht geschlossen und ich muss es manuell öffnen.
Es wäre prima, wenn man es so konfigurieren könnte, wenn nicht die Höchstzahl erreicht ist, bleibt die Schicht offen oder wird wieder geöffnet.

**Comment by MarvinZeising** [comment]
Sollte mittlerweile gelöst sein.
