### ISSUE TITLE
Fehler - Liste der angelegten VK zur Einladung

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#108]
Hallo,

ich habe jetzt einen neunen VK angelegt und eingeladen.
Bisher waren in der Liste nur die "neuen" drin. Jetzt ist die Liste mega groß. Habe das Gefühl, da sind alle drin.
Liegt das daran, dass wir das zweite Projekt jetzt offen haben?

**Comment by Daniel-vhm** [comment]
Ja, bei mir werden alle angezeigt, aber irgendwie funktioniert es nicht zuverlässig, dass die bereits eingeladenen ich wirklich "orange" werden. 

Zumindest erscheinen die zuletzt angelegten am Ende der Liste...

**Comment by MarvinZeising** [comment]
Fehler wurde gelöst. Es werden nur noch Benutzer des aktuellen Projektes angezeigt.
Für die Sortierung lege ich eine eigene Issue an.
