### ISSUE TITLE
Button "Teilnahme absagen" funktioniert nicht

### ISSUE THREAD

**Issue by Thomasks8** [JWDeveloper/JWManagement#109]
Möchte ich mich als Bruder aus einer Schicht austragen über ->Button "Teilnahme absagen", ->Button "Bewerbung zurückziehen", erscheint immer folgende Fehlermeldung bei mir:

"Error 550"
"This user is not a shift manager"

Falls ich mich kurzfristig austragen muss, wäre es schnell wichtig, damit ein anderer Bruder noch Zeit hat, die Schicht zu übernehmen. LG

**Comment by MarvinZeising** [comment]
Wurde mit 1.0.12 behoben.
