### ISSUE TITLE
Teilnehmerliste Benutzernamen anzeigen

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#11]
In der Teilnehmerliste kann ich nicht den Benutzernamen einsehen.
Ich kann zwar im Suchfeld nach dem Benutzernamen suchen, aber er wird mir nicht in der Ergebnisliste ausgegeben. Im Pulldown Menü neben dem Suchfeld kann ich als Option den Benutzernamen auswählen. Dann würde ich aber erwarten das eine Spalte mit den Benutzernamen ausgegeben wird, wenn ich die Option den Benutzernamen auswählt habe. Eine Detail Seite für den angeklickten Teilnehmer mit allen Daten fehlt noch.

**Comment by tim-antkowiak** [comment]
Hallo Mario,
wenn du auf eine Zeile in der Teilnehmerliste klickst, oder auf das + am Anfang der Zeile, sollte sich ein Bereich mit weiteren Informationen zu diesem Verkündiger öffnen. Da steht dann auch der jeweilige Benutzername.
Das Pulldown Menü neben dem Suchfeld ist lediglich dafür da um zu bestimmen in welchen Attributen nach dem Schlüsselwort gesucht werden soll.

**Comment by schillermann** [comment]
Ich würde empfehlen die Auswahlliste für die Suche zu entfernen.
Sie verwirrt mehr als das sie einem was nützt.
Oder man setzt neben dem Suchfeld ein Pulldown Menü wo man eine einzelne Auswahlmöglichkeit hat nach welchem Typ man sucht, ob nach der E-Mail Adresse oder den Benutzernamen.
Wenn kein Typ ausgewählt wurde kann in jedem Typ gesucht werden.

**Comment by schillermann** [comment]
Bei einer Liste mit Checkboxen gehe ich im ersten Moment ohne groß zu überlegen davon aus das ich hier die anzuzeigenden Spalten auswählen kann.

**Comment by tim-antkowiak** [comment]
Okay, danke für den Vorschlag, ich nehme das auf.
Den Benutzernamen hast du gefunden?

**Comment by schillermann** [comment]
Macht es denn Sinn das mehrere Typen für die Suche ausgewählt werden sollen?
Wenn ich nach dem Benutzernamen suchen will möchte ich nicht erst alle anderen Optionen deaktivieren.
Wie hoch ist die Wahrscheinlichkeit das man z.B. die E-Mail Adresse in allen Typen suchen möchte?

**Comment by tim-antkowiak** [comment]
Je mehr Attribute man durchsucht, umso höher ist die Wahrscheinlichkeit den richtigen Teilnehmer im Ergebnis zu haben und der User brauch sich keine Gedanken machen nach welcher Art von Attribut er genau suchen will.
Aber ich nehme das mal in die nächste Besprechung mit rein. Wenn die Auswahlliste mehr verwirrt als hilft nehmen wir sie raus.

**Comment by schillermann** [comment]
Die Option alle Typen durchsuchen zu können an sich ist ja ok.
Man muss das halt von der Warte aus sehen wie die Suchfunktion am häufigsten genutzt wird.
Ein Benutzer hat entweder einen bestimmten Typ im Sinn nach dem er suchen will oder er will alle Typen durchsuchen. Ich glaube nicht das sich ein Benutzer die Mühe macht einzeln die Checkboxen zu aktivieren oder zu deaktivieren. Der Benutzer möchte so schnell wie möglich zu seinem Ziel kommen etwas zu finden. Siehe das Beispiel von Amazon mit dem 1-Click kaufen Prinzip.

**Comment by tim-antkowiak** [comment]
Genau deswegen wird auch standardmäßig in allen Typen gesucht, sodass der "Durchschnittsuser" ohne großen Aufwand schnell an sein Ziel kommt.
Aber die Checkboxen durch ein einfaches Dropdown zu ersetzen in dem man einen einzelnen Typ auswählen kann macht vielleicht schon Sinn. 
Danke für den Vorschlag!

Ich schließe mal das Issue, da das eigentliche Thema ja geklärt ist.
