### ISSUE TITLE
Anmeldung nicht möglich

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#112]
Berichtet von @DerwerteFreund:
Verkündiger berichten, dass sie Probleme mit dem Passwort haben. Das erste mal können sie sich mit ihrem Passwort bei JW Management einloggen. Wenn sie sich dann wieder ausloggen, wird das Passwort nicht mehr akzeptiert. Nach Rücksetzung des Passwort und Vergabe eines neuen, ist der Zugang wieder möglich - jedoch auch nur einmal.

**Comment by MarvinZeising** [comment]
Hört sich nach einem Problem mit dem Benutzernamen an.
Wenn dort Sonderzeichen verwendet werden (wie z.B. @ und .) klappt die Anmeldung nicht mehr.
Die betreffenden Verkündiger sollten ihren Benutzernamen einfach mit der nächsten Anmeldung ändern, damit sollten sich die Probleme lösen.
Ich werde mal einen erklärenden Hinweis über dem Benutzernamensfeld einblenden.

**Comment by DerwerteFreund** [comment]
Der Benutzername war in einem Fall "Irene" - enthielt also keinerlei Sonderzeichen.

**Comment by MarvinZeising** [comment]
Ich kann beim genannten Account keine Unregelmäßigkeiten erkennen...
Besteht das Problem immernoch? Wenn ja, melde dich bitte mal bei mir.
Dann können wir das Passwort zusammen zurücksetzen und schauen, ob sich ein Anwenderfehler ausschließen lässt.
Bis dahin schließe ich die Issue vorerst einmal.
