### ISSUE TITLE
Mail "Team unterbelegt" mit irreführender Text?

### ISSUE THREAD

**Issue by DerwerteFreund** [JWDeveloper/JWManagement#113]
Die versendete Email zum Thema "Team unterbelegt" enthält den Text:
"Hallo Sven Klosse, 
das folgende Team ist unterbelegt und benötigt noch einen Teamleiter"

Der Bruder, der bereits in der Schicht steht, ist jedoch als Teamleiter eingetragen und dementsprechend werden nur noch Verkündiger aber keine Teamleiter mehr benötigt.

**Comment by MarvinZeising** [comment]
Notiz an mich:
Fehler tritt auf, wenn in den Teilnehmern **kein** Teamleiter ist, wohl aber in den **offenen** Bewerbungen. Die werden beim Versenden der Mail nicht mit einbezogen.
