### ISSUE TITLE
Fehler - geschlossene Schichten "blau"

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#114]
Hallo,

in der heutigen Woche sind alle Schichten, ob offen oder geschlossen blau.
Sonst waren die geschlossenen doch grau und die offenen blau.
Ist das geändert und wenn ja, mit welchen Hintergrund?

**Comment by alisander2** [comment]
jetzt sind in der Woche die ersten drei Schichten heute grau, alle anderen blau
Ist das nach zeitlichem Ablauf?

**Comment by MarvinZeising** [comment]
Der Fix wird gerade deployed.
