### ISSUE TITLE
Mailto E-Mail Programm öffnet sich nicht bei 60 User Adressen

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#115]
Wenn ich eine Email an bestimmte User schicken möchte und dafür auf den E-Mail an ... Button klicke öffnet sich kein E-Mail Programm. Erst wenn ich im Html beim Link Attribut die E-Mail Adresse z.B. auf 6 E-Mail verkürze, öffnet sich mein Outlook Mail Programm.

**Comment by MarvinZeising** [comment]
Geht bei mir einwandfrei.
Apple Mail öffnet sich sofort mit allen gewünschten Empfängern.
Hab's auch direkt mit deinem Projekt getestet.

Problem von Outlook?
Kann man den Link anpassen, so dass auch Outlook mit vielen Empfängern klarkommt?

**Comment by tim-antkowiak** [comment]
Das sieht mir eher nach einem Windows Problem in Verbindung mit mailto aus. Ruft man den Link mit Firefox auf, öffnet sich Outlook, übernimmt aber "nur" ungefähr die ersten 1900 Zeichen.

Bei mir funktioniert es, wenn ich wie du in das HTML Attribut gehe, den Mailto-Link kopiere und in Outlook einfüge (natürlich noch das "mailto:?bcc=" am Anfang entfernen). 

Vielleicht macht hier in Zukunft ein kleines Dropdown sinn, in dem man dann eine Textbox mit allen Adressen zum kopieren findet.

**Comment by schillermann** [comment]
Tim das ist eine sehr gute Idee.
Ich weiß jedoch nicht ob ältere junggebliebene damit klar kommen.
Die sind froh wenn sie das richtige Knöpfchen zum senden gefunden haben.
Einen eigenen Mail Versand habt ihr nicht?

Wenn ich in meiner Outlook Mail App mehrere Adressen eintrage trennt er die Adressen mit einem Semikolon, mit einem Komma kann Outlook nichts anfangen.

**Comment by tim-antkowiak** [comment]
Ja, für ältere könnte das etwas schwieriger sein. Wir werden das mal in unser nächstes Meeting mitnehmen, was wir da am besten machen. Danke!

Du hast recht, Outlook trennt mit Komma und nicht mit Semikolon. Bei mir funktioniert es wenn ich nach dem Einfügen der Adressen oben im Menü den Button "Namen überprüfen" drücke. Dann werden alle Adressen mit Namen von Outlook auf Plausibilität geprüft und die Kommata durch Semikolons ersetzt.

**Comment by alisander2** [comment]
Wenn ich mit Google Chrome eine Email senden möchte, geht es auch nicht. Ich klicke dort drauf, aber es passiert dann gar nicht mehr,

**Comment by schillermann** [comment]
Hier eine Idee für das Kopieren von E-Mail Adressen.
In dem Button E-Mail an könnte man ein Pfeil mit einbauen.
Wenn man direkt auf den Pfeil klickt würden darunter Zusatzfunktionen erscheinen z.B. mit Adressen kopieren.
So wird das im Prestashop gemacht, wenn ein Button Zusatzfunktionen benötigt.
In diesem Screenshot kannst du das an dem Edit Button sehen.
https://www.prestashop.com/blog/de/files/2014/02/ProductsBeta.png

**Comment by MarvinZeising** [comment]
Den Button zum Kopieren gibt es mittlerweile. Daher schließe ich den Thread mal.
