### ISSUE TITLE
Edit-Vorlagewochen: Ändern des Tags in einer Schicht 

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#117]
Ändert man beim anlegen eine Vorlagewoche, den tag einer Schicht.  Wird diese Schicht in der aktuellen Vorlagewoche gespeichert, jedoch ist sie nicht mehr zu sehen! Unter den jeweiligen Wochentag erkennt man das Symbol Alles löschen, aber die Schicht mit dem geänderten Tag nicht mehr.
Legt man eine Woche mit dieser Vorlage an, wird diese Schicht mit dem geänderten Tag mit angelegt.

Eine Vorlagewoche mit unterschiedlichen Tags anzulegen ist durchaus Intressant! Den die Benutzerrechte der Teilnehmer-Tags greifen! 
So kann ich mit einer Vorlage für alle Teilnehmer unterschiedliche Schichten anzeigen lassen. 

Bitte läßt eine Schicht mit  geänderten Tags in der Vorlagewoche sichtbar erscheinen.

**Comment by MarvinZeising** [comment]
Wurde mit Release 1.0.15 geändert 👍🏼
