### ISSUE TITLE
Fehler Ausgeblendete Tags werden trotzdem angezeigt

### ISSUE THREAD

**Issue by alexlaux** [JWDeveloper/JWManagement#119]
In der Wochenansicht werden, seit heute, plötzlich auch die Schichten angezeigt, die man nicht sehen möchte. Somit hat man nun keine Tag-weise Schichtansicht, es werden einfach alle angezeigt.

**Comment by alexlaux** [comment]
kleines Update: trotz der fehlender Berechtigung werden alle Schichten angezeigt und man kann sich auf alle Schichten bewerben

**Comment by MarvinZeising** [comment]
Wird gleich behoben 👍🏼

**Comment by MarvinZeising** [comment]
Wurde gerade behoben.

**Comment by alexlaux** [comment]
Super das ging ja fix. Vielen Dank
