### ISSUE TITLE
Nur 2 Wochen kann der Teilnehmer auswählen

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#12]
Schichten vom 2.1 - 8.1 und vom 9. - 15.1 können vom Teilnehmer auswählt werden.
Nachfolgende Wochen hat nur der Administrator in der Auswahlliste.

**Comment by schillermann** [comment]
Mit dem Pfeil Button komme ich in die nächste Woche rein.
Erst dann wird sie mir in der Auswahlliste angezeigt.

**Comment by alisander2** [comment]
Ja, das Problem taucht bei uns bei den VK auch auf und hat schon zu Verwirrung geführt.

**Comment by schillermann** [comment]
Ist die Änderung schon live?
Bei Teilnehmern besteht das Problem immer noch.

**Comment by MarvinZeising** [comment]
Negativ.
Sobald der Fehler bereinigt ist, wird die Issue geschlossen, damit wir eine ordentliche Übersicht behalten können während wir die Issues abarbeiten.
Welche Änderungen live gegangen sind, kannst du dem master entnehmen, welcher stets den Stand der Live-Version hat. Oder dem Changelog auf der Startseite.
Im Allgemeinen gehen wir mit Änderungen gerne spät Abends oder Nachts live. Falls dabei Fehler oder sogar Down-Zeiten auftreten, bekommen es dadurch nur wenige Benutzer mit.

**Comment by schillermann** [comment]
Wie wäre es beim schliessen folgendes zu scheiben: Der Fehler wurde behoben und geht mit den nächsten Updates online.

Du kennst den Ablauf, diejenigen die euch schreiben nicht.

**Comment by schillermann** [comment]
Wie wäre es beim schliessen folgendes zu scheiben: Der Fehler wurde behoben und geht mit den nächsten Updates online.

Du kennst den Ablauf, diejenigen die euch schreiben nicht.

**Comment by MarvinZeising** [comment]
Gute Idee 👍🏼
