### ISSUE TITLE
Benutzername vergessen

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#120]
Sehr oft wird nicht nur das Passwort sondern auch der Benutzername vergessen.
Könnt ihr eine Benutzername vergessen Funktion mit einbauen?

**Comment by MarvinZeising** [comment]
Naja für die Passwort vergessen Funktion braucht man ja keinen Benutzernamen. Nur die E-Mail Adresse. Und dann wird man direkt eingeloggt und kann im Profil seinen Benutzernamen nachsehen.
Man könnte den Benutzernamen allerdings auch mit in die Reset-Mail schreiben, wäre vielleicht gar keine schlechte Idee.

**Comment by schillermann** [comment]
Soweit wird da nicht gedacht.
Werde halt oft nach dem Benutzername gefragt.
