### ISSUE TITLE
Telefonnummern fehlen

### ISSUE THREAD

**Issue by kevin-richter** [JWDeveloper/JWManagement#121]
Beim Versenden von Zuteilungen und Unterbesetzt-Mails fällt uns immer wieder auf, dass einige Telefonnummern in der Mail fehlen.

**Ein Beispiel:**
Bei vier Teilnehmern werden von zwei Verkündigern die Nummern angezeigt und von zweien aber nicht.

Im Benutzerprofil sind die Nummern aber jeweils hinterlegt. Woran kann das liegen?

**Comment by MarvinZeising** [comment]
Das ist mir neu.
Kannst du feststellen, ob die Telefonnummern der betreffenden Accounts generell nie gezeigt werden, oder ob quasi zufallsmäßig verschiedene Nummern fehlen?

**Comment by kevin-richter** [comment]
Ich habe das jetzt einige Zeit beobachtet. Leider konnte ich bislang noch keine Regelmäßigkeit erkennen.

- es gibt Verkündiger da wird die Nummer nie angezeigt
- bei manchen wird sie mal angezeigt und dann wieder nicht
- die betreffenden Verkündiger haben ihre Nummern in den unterschiedlichsten Formaten hinterlegt (Leerzeichen, +49, 0049, ...); bei einigen geht es damit und bei anderen nicht

Aber ich werde das weiter beobachten - vielleicht fällt mir noch etwas auf ...

**Comment by kevin-richter** [comment]
Der Fehler ist bislang nicht wieder aufgetreten. Das Thema kann deshalb geschlossen werden.
