### ISSUE TITLE
Teilnehmerzahl + Kalenderdatei

### ISSUE THREAD

**Issue by BenKrueger84** [JWDeveloper/JWManagement#123]
Hey...
Erst einmal danke für eure Mühen... 
2 Fragen oder Anregungen hätte ich.

1.) Wir wollen die Schichten manuell bestätigen, die Verkündigen sehen erst bei der Bestätigung mit wem Sie unterwegs sind. Könnt ihr dennoch in der "Bewerbungsphase" noch eine Auslastung der Schichten anzeigen... Im Moment erscheint jede Schicht leer.. Man sieht nur seine eigenen Bewerbungen. Eine Zahl der Bewerbungen oder eine prozentuale Auslastung wäre auch für die Verkündiger interessant... Wie beim ÖZB.

2. )Wenn eine Schicht geschlossen ist, wäre es praktisch wenn in der Bestätigungsmail eine Kalender Datei verschickt wird, die direkt in den persönlichen Kalender übertragen werden kann (.ics)
LG aus Berlin

**Comment by tim-antkowiak** [comment]
Hi!
Danke für deine Anregungen. Ersteres haben wir schon notiert und werden wir so bald wie möglich einbauen.
Der 2. Punkt ist auch eine gute Idee. Momentan haben aber andere Punkte Priorität (App, Restructuring, etc.). Wenn die fertig sind, werden wir uns da mal dran machen. 
Danke!

**Comment by MarvinZeising** [comment]
Die Auslastung der Schichten wurde hinzugefügt, die Kalenderdatei dürfte sich wegen der Zeitzone als problematisch erweisen. Das System kann nicht feststellen, auf welchem Kontinent bzw. in welcher Zeitzone der Benutzer lebt, daher wäre die Uhrzeit des durch Datei erstellten Termins bei den meisten Nutzern wahrscheinlich falsch.
