### ISSUE TITLE
Passwort und Benutzernamen als Administrator für andere ändern

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#126]
Ich habe die Situation das eine Schwester zwar meine Test Mail bekommen hat, aber nicht die Mail vom JWManagement mit dem Passwort.
Hier würde es den Prozess bei unbeholfenen vereinfachen wenn ich für sie das Passwort und den Benutzernamen setzten kann und es ihnen mündlich übermitteln kann.

**Comment by MarvinZeising** [comment]
Ist mittlerweile möglich.
