### ISSUE TITLE
Depot Literatur hinzufügen

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#127]
Vor eurem großen Update konnte man unter Depot ganz einfach neue Literatur hinzufügen.
Jetzt hat man nur die Möglichkeit auf "Zeige alle Puplikationen" zu klicken und dann wird die Literatur Liste als Check Liste angezeigt.
Aber wo kann ich neue Literatur hinzufügen oder die Menge ändern?
![depot](https://cloud.githubusercontent.com/assets/13864946/25061622/eccaa290-21ba-11e7-95c4-02035527f77e.jpg)
![depot-uebersicht](https://cloud.githubusercontent.com/assets/13864946/25061625/f0648ab0-21ba-11e7-9926-44231ea8b291.jpg)

**Comment by MarvinZeising** [comment]
Du musst eine Publikation anklicken.
Dann erscheinen rechts die Einstellungen für die gewählte Publikation.
An die Seite müssen wir denke ich definitiv noch einmal dran.

**Comment by schillermann** [comment]
Danke dir.
Es ist schwierig unterscheiden zu können welcher Text interaktiv ist und welcher nur Text ist.

**Comment by alexlaux** [comment]
Hallo ihr lieben, wenn ihr an die Seite dran geht, dann denkt bitte auch an die Sprachen, so dass man diese auch selbst anlegen kann und die Sortierung sollte automatisch alphabetisch sein, (aktuell ist es nicht so). 
![sprachensortierung](https://cloud.githubusercontent.com/assets/25442872/26348667/b8a55c9c-3fad-11e7-800d-d22a137acfa2.jpg)

**Comment by MarvinZeising** [comment]
Um das Problem der Usability zu verbessern, wird nun hinter den Publikation ein Icon dargestellt, das anzeigen, dass ein Klick auf den Titel der Publikation etwas öffnet.
Außerdem wird die Liste der Sprachen nun alphabetisch sortiert.
Dass man keine Sprachen hinzufügen kann ist Absicht.
Wenn weitere Sprachen benötigt werden sollten, sollte das an den Support geschrieben werden, dann fügen wir diese hinzu.
