### ISSUE TITLE
Teambeschreibung

### ISSUE THREAD

**Issue by kaideutschlaender** [JWDeveloper/JWManagement#128]
Zwei Teams sind erstellt. Unterschiedliche Beschreibung. Wenn ich in der Schicht, das zweite Team auswähle, kommt die Beschreibung vom 1. Team. Hochgeladenes Bild wird aber vom 2. Team angezeigt.

**Comment by MarvinZeising** [comment]
Danke für den Fehlerbericht.
Beim Eintragen des Teams in die Schicht wird die falsche Beschreibung ausgewählt.

Temporärer Fehlerfix:
Sobald man allerdings die Beschreibung des betreffenden Teams ändern, wird sie auch korrekt in allen Schichten geändert, wo dieses Team eingetragen ist.
Das habe ich für deinen Fall schon mal gemacht und auch überprüft.
