### ISSUE TITLE
Token Fehler bei Anmeldung

### ISSUE THREAD

**Issue by Archipuss** [JWDeveloper/JWManagement#130]
Hallo,

eine Schwester erhält die Fehelrmeldung: Token Fehler. Bitte wende dich an den Administrator(Support@jwmanagement.org) oder dein Projektleiter.

Was ist die Ursache? Was können wir machen?
danke

Grüße

**Comment by kepano75** [comment]
Die Einladung nochmal sende, hat bei mir mal geholfen. lg Stephan

**Comment by Daniel-vhm** [comment]
Den Link in der Einladungsmail nur zum ersten Aufruf benutzen! Danach einfach jwmanagement.org aufrufen und mit "Benutzername", "Passwort" anmelden.....
Vielleicht kann man da eine "automatische Umleitung" einbauen, wenn der Benutzer bereits angelegt wurde...???

**Comment by mh166** [comment]
Leider hab ich nur "normale" JS-Erfahrung. Daher kann ich hier kein PR anbieten. 😕 

Aber wenn ich das richtig interpretiere, könnte man in [mainRoutes.coffee#L55](https://github.com/JWDeveloper/JWManagement/blob/a8c029bcaf0b3615a270075762a6bf638c7667c6/imports/startup/client/mainRoutes.coffee#L55) einen neuen [Helper](https://github.com/JWDeveloper/JWManagement/blob/develop/imports/startup/client/routeHelpers.coffee) hinzufügen, z.B. `checkValidToken`. Dieser sollte prüfen, ob das Token noch "frisch" und gültig ist.

Ist das Token ungültig (z.B. nicht in der DB oder gar kein Token übergeben), kann eine Fehlermeldung angezeigt werden. Ist das Token zwar gültig, wurde aber bereits verwendet, so sollte hier auf die normale Login-Seite weitergeleitet werden.

Ich hoffe, ich hab den Code richtig verstanden. Andernfalls einfach ignorieren. 😅

**Comment by MarvinZeising** [comment]
Soeben habe ich, denke ich, den Token-Fehler behoben.

Wenn der Verkündiger beim Ausfüllen des Formulars einen Benutzernamen gewählt hat, den es bereits mit anderen Groß- oder Kleinbuchstaben gab, konnte der Server den Benutzernamen nicht setzen, da er ihn intern in Kleinbuchstaben umwandelt und die Benutzernamen damit gleich wären.

Allerdings wurde das nicht korrekt an den Client kommuniziert, was ich nun korrigiert habe.

Ich hoffe, dass das den "Token-Fehler" komplett löst.
