### ISSUE TITLE
Fehler - Benutzer gelöscht, in allen Projekten weg

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#135]
Wenn ich einen Benutzer, der in einem anderen Projekt auch vorhanden ist, anlege und diesen dann wieder lösche, dann ist er in allen Projekten gelöscht.
Ist uns jetzt mit einem Projekt passiert und derjenige hat dann die Admis im anderen Projekt gelöscht.

**Comment by MarvinZeising** [comment]
Sollte durch den referenzierten Commit (s.o.) gelöst sein
