### ISSUE TITLE
Vorschlag: Für jedes Tag ein eigenes Depot

### ISSUE THREAD

**Issue by kevin-richter** [JWDeveloper/JWManagement#136]
Wir nutzen in unserem Projekt 3 Tags (Trolley, Infostand, Trolley Asylheim). Momentan ist es so, dass die im Schichtbericht als abgegeben eingetragenen Publikationen von dem einen elektronischen Depot abgezogen werden.

Wir haben in unserem Königreichssaal aber für jeden der 3 Dienstzweige einen eigenen Vorrat zum Nachfüllen. Dafür sind auch jeweils verschiedene Brüder zuständig.

**Wäre es programmierbar, dass man für jedes Tag ein eigenes elektronisches Depot einrichten kann?**

So wäre es nebenbei auch möglich, die Zusammenstellung der Publikationen besser auf den jeweiligen Zweck zuzuschneiden.

**Comment by MarvinZeising** [comment]
Im Moment ist das leider nicht möglich, tut mir leid.
