### ISSUE TITLE
Fehler beim löschen von manuell hinzugefügten Verkündigern

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#137]
Wenn man Verkündiger löscht, werden diese mal durchgestrichen angezeigt und manchmal sind diese völlig raus ...

**Comment by MarvinZeising** [comment]
Ich kann den Fehler leider nicht nachstellen.

Wie hast du die Verkündiger gelöscht?
Über selektieren und dann selektierte ablehnen? Oder einzeln über den Daumen runter? Oder indem du das Team abgesagt hast?
Wie viele Teilnehmer waren in dem Team? Und gab es noch offenen Bewerbungen oder bereits abgelehnte?

**Comment by kepano75** [comment]
ist etwas kompliziert..
Teilnehmer wurde via Verkündiger hinzufügen eingetragen. Hat sich selbst zurück genommen und wurde daher in Status Orange versetzt. Merkwürdigerweise wurde automatisch weitere Verkündiger diesem Team eingetragen. Ich konnte keinen dieser Verkündiger mit Daumen runter löschen. Auch Team absagen hat nicht bewirkt das das Team geschlossen wird. 
Nachdem die Website kurz abgestürzt oder einen Neustart durchgeführt hatte, konnte ich die Teilnehmer wieder löschen. 
das war kurz nach dem ich das Ticket geschrieben hatte. 
gruß Stephan 
		

		Outlook für iOS beziehen
	





On Wed, Aug 30, 2017 at 10:39 PM +0200, "Marvin Zeising" <notifications@github.com> wrote:












Ich kann den Fehler leider nicht nachstellen.


Wie hast du die Verkündiger gelöscht?

Über selektieren und dann selektierte ablehnen? Oder einzeln über den Daumen runter? Oder indem du das Team abgesagt hast?

Wie viele Teilnehmer waren in dem Team? Und gab es noch offenen Bewerbungen oder bereits abgelehnte?

**Comment by kepano75** [comment]
Fehler ist nicht mehr aufgetreten... seid dem man Verkündiger nur noch einmalig pro Schicht hinzufügen kann.
