### ISSUE TITLE
Fehler in der Schichtanzeige

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#138]
![image](https://cloud.githubusercontent.com/assets/24896263/26824179/93b0512c-4ab0-11e7-8220-78bb66b1b08c.png)

Diejenigen, die aus der Schicht raus sind, werden nicht angezeigt. Aber die, die noch drin sind werden weiterhin als Teilnehmer und abgesagt angezeigt.

**Comment by MarvinZeising** [comment]
Ich kann den Fehler leider nicht nachstellen.

Wie hast du die Verkündiger gelöscht?
Über selektieren und dann selektierte ablehnen? Oder einzeln über den Daumen runter? Oder indem du das Team abgesagt hast?
Wie viele Teilnehmer waren in dem Team? Und gab es noch offenen Bewerbungen oder bereits abgelehnte?

Ich nehme überdies an, dass das hier ein duplicate of #137 ist.
