### ISSUE TITLE
Tag löschen

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#14]
Wenn ich einen Tag löschen möchte bekomme ich eine Abfrage mit einem Eingabefeld.
Aus dem Text dadrüber geht nicht hervor was hier eingetragen werden soll.
Erst die Fehlermeldung weißt einen drauf hin.

**Comment by tim-antkowiak** [comment]
Ja, da haben wir den den Text noch nicht angepasst. Danke für den Hinweis, wir kümmern uns drum!
