### ISSUE TITLE
Fehler- "neue Woche anlegen" mit Vorlage 

### ISSUE THREAD

**Issue by Daniel-vhm** [JWDeveloper/JWManagement#141]
Manchmal wird die Auswahl der entsprechenden Vorlage nicht sauber nach "oben" mitgenommen. Das Feld ist dann "leer"...

Drückt man jetzt auf anlegen, wird die Woche mit der "ersten Vorlage" aus der Liste gefüllt. 
Wenn man nicht aufpasst führt das zu Problemen.

**Comment by MarvinZeising** [comment]
Von welchem Projekt sprechen wir? Welche Vorlagen gibt es? Ist das Problem reproduzierbar? Wenn ja, wie? Welche Vorlage muss ich dafür auswählen?

**Comment by MarvinZeising** [comment]
Konnte das Problem leider nicht reproduzieren.
Das Popup wird aber sowieso bald neu gemacht, dann sollte sich das geben.
Ich bin mal so frei und schließe das hier.
