### ISSUE TITLE
Probleme Einladungslink

### ISSUE THREAD

**Issue by MathiasWohlgemuth** [JWDeveloper/JWManagement#144]
Wir haben das Problem, dass manche Verkündiger sich nicht für JWManagement registrieren können. 

Beim öffnen des Einladungslink wird ihnen angezeigt, dass dieser nicht mehr gültig ist. 

Ein manuelles löschen, neu anlegen und nochmal neuen Link verschicken löst das Problem leider nicht. 

Ist das Problem bekannt bzw gibt es eine Lösung?

Liebe Grüße

Mathias

**Comment by MarvinZeising** [comment]
Wir haben im Moment leider keine Ahnung, was hier das zugrunde liegende Problem ist.
Ich habe es bei solchen Fällen schon einige Male selbst probiert, allerdings klappt es bei mir immer problemlos. Daher habe ich das Gefühl, dass es sich hier um einen Bediener-Fehler handelt. Leider kann ich nicht sagen, was genau falsch gemacht wird. Wäre daher dankbar, wenn jemand mit so einem Problem genauere Informationen darüber geben könnte, auf/mit was für einem System er/sie arbeitet und was genau er/sie gemacht hat.

**Comment by MarvinZeising** [comment]
Closed in favor of #130
