### ISSUE TITLE
Welcher Benutzer hat sich schon angemeldet

### ISSUE THREAD

**Issue by Daniel-vhm** [JWDeveloper/JWManagement#145]
Gerade beim Start eines großen Projekts gibt es eine "Menge" Personen, die sich einfach nicht zeitnah anmelden.
Gründe gibt es verschiedene:
- Falsche e-mail Adresse
- Mails landen im SPAM Ordner
- Mangelnde "Skills" des Benutzers.

Im Moment kann man nur über den Benutzernamen erkennen, Ob sich jemand schon einmal angemeldet hat.
Es wäre schön, wenn man das aufgrund eines Merkmals einfach filtern könnte.
Es würde schon langen, wenn man das als "TAG" im Export (csv) der Benutzer erkennen konnte.

**Comment by 51773ELLIS** [comment]
@MarvinZeising Would this be implementing a search filter for users? I think we have spoken about this before.

**Comment by MarvinZeising** [comment]
Benutzer, die sich bereits angemeldet haben, werden nun grün dargestellt.
