### ISSUE TITLE
Export der Benutzerdaten

### ISSUE THREAD

**Issue by Daniel-vhm** [JWDeveloper/JWManagement#146]
Wäre es möglich, die Berechtigung des Benutzers im Projekt und ggf. in den einzelnen "Tags" beim Export mit auszugeben?

**Comment by tim-antkowiak** [comment]
Hi,
das ist in einer CSV Datei leider relativ schwer zu realisieren, da jeder User beliebig viele Berechtigungen haben kann, je nachdem wie viele Tags es gibt.
Aber du hast Recht, grundsätzlich ist das eine gute Idee.

**Comment by mh166** [comment]
Was hälst du von einer Spalte `Rollen`, in die man dann in einer Liste als Wertepaare (ähnlich einer INI-Datei) die Tags mit zugehörigen Berechtigungen schreibt?

In der Liste kann man dann entweder ein anderes Trennzeichen als im Rest verwenden (z.B. `,` oder `#` statt `;`). Oder der Wert für die Spalte wird in Anführungszeichen gesetzt. Dann dürfte auch nix damit passieren – zumindest hat sich Excel bei meinem Test nicht beschwert und alles brav komplett in eine Spalte geschrieben.

Das Ergebnis könnte dann zum Beispiel so aussehen:
```
...;Benutzername;Rollen
...;mh166;"Trolley=teamleader;Fernfahrer=participant"
```

**Comment by MarvinZeising** [comment]
Die Spalte ist nun eingebaut. Allerdings nicht mit dem Projekt Namen, sondern der ID.
Somit kannst du anhand der ID alle Projekte identifizieren, für die du auch Berechtigungen hast.
Wird heute abend live gehen.
