### ISSUE TITLE
Schichtdaten bearbeiten Usability

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#15]
Wenn ich eine neue Schicht in der Vorlage angelegt habe, bin ich davon ausgegangen das ich nach Eingabe der Daten auf "Schicht einteilen" klicken muss. In den meisten Anwendungen ist man gewohnt auf den erstellen oder speichern Button zu klicken. Vielleicht kann man dem Eindruck entgegen wirken wenn der "Löschen" und "Schicht einteilen" Button in eine separate Zeile dadrüber als Option gekennzeichnet gesetzt wird.

**Comment by MarvinZeising** [comment]
Bei JWManagement muss man nirgendwo speichern. Das sollte jeder Anwender eigentlich recht schnell merken. Immerhin muss man ja schon im Profil nichts speichern.

Alles, was ich mir als separate Zeile vorstellen kann, sähe ziemlich bescheiden aus. Daher finde ichs eigentlich ganz gut so wie es ist. Es ist ja auch kein Schicht-Erstellungsmodal, sondern einfach nur das zum Bearbeiten von Schichten. Der "Erstellungsprozess" ist ja schon abgeschlossen, wenn dieses Modal kommt.

Was man aber machen könnte, wäre Toasts wie im Profil einzuführen. Dann wäre zumindest klar, dass man seine Änderungen nicht speichern muss.
Und beim Klick auf Plus-Button könnte man das ja auch anzeigen, dann wäre klar, dass die Schicht Berits erstellt wurde.

**Comment by schillermann** [comment]
Vielleicht reicht es auch aus den Button "Schicht einteilen" auf "Teilnehmer Bewerbung", "Teilnehmer" oder was ähnlichen umzubenennen. Dann bringt man den Button nicht mehr damit in Verbindung das hiermit keine Schicht Erstellung abgeschlossen wird.
Das sind aber alles nur Vorschläge die das Ziel haben älteren die Bedienung zu erleichtern.

**Comment by MarvinZeising** [comment]
Da der Vorschlag anscheinend hinreichend umgesetzt wurde, schließe ich die Issue
