### ISSUE TITLE
'Verknüpfte Information ansehen' -> falsch verlinkt

### ISSUE THREAD

**Issue by edonadeo** [JWDeveloper/JWManagement#151]
Situation:
Es existieren mehrere Teams. Beim manchen ist eine Link gepflegt. Bei dem Team 'Infostand' jedoch nicht.
Der Link 'Verknüpfte Information ansehen' wird trotzdem angezeigt und verlinkt auf den Link von einem anderen Team (der Link vom ersten Team?).

![image](https://user-images.githubusercontent.com/31246045/30001725-afbbd40a-9096-11e7-961d-81aaf7160eed.png)

**Comment by MarvinZeising** [comment]
Hier besteht in der Art ein Bug, dessen Ursache ich leider noch nicht gefunden habe.
Allerdings gibt es einen Workaround um zum gewünschten Ergebnis zu kommen:
Sobald in den Einstellungen der Link in dem Team geändert wird (also z.B. Text löschen und dann Text wieder einfügen), wird der "neue" Text für alle Schichten übernommen. Damit werden dann auch die Schichten/Teams korrigiert, bei denen ein falscher Link angegeben ist.
Der gleiche Workaround kann auch für die Beschreibung angewendet werden, falls da etwas spinnt.
