### ISSUE TITLE
Dummy Daten nach dem Anlegen einer Schicht

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#16]
Nach dem Anlegen einer Schicht sehe ich zum Teil Dummy Daten die normalerweise nur beim Laden der Schichten Seite kommen.
![2017-01-03](https://cloud.githubusercontent.com/assets/13864946/21610785/5b8bd136-d1ca-11e6-9f94-2c60e259decb.png)

**Comment by MarvinZeising** [comment]
Du meinst, dass man die dummys anpassen könnte, um besser das Layout dieser Schicht Ansichten widerzuspiegeln? Da gebe ich dir recht.
Oder meinst du, die dummys laden nicht, sondern bleiben dummys?

**Comment by schillermann** [comment]
Sie bleiben Dummies wie du im Screenshot sehen kannst. Aber das ist mir bis jetzt nur einmal passiert.

**Comment by MarvinZeising** [comment]
Ich schließe das mal, bis ich oder jemand anderes den Fehler reproduzieren kann.
