### ISSUE TITLE
Problem bei Berichtsabgabe

### ISSUE THREAD

**Issue by Aaron-Gruber** [JWDeveloper/JWManagement#163]
Hallo liebe Brüder,
uns ist aufgefallen, dass die Brüder und Schwestern ab und zu keine Berichte über JW Management abgeben können. 
Es wird z.B. die eben berichtete Literatur nicht angezeigt. Interessanterweise sehe ich als Admin die berichtete Literatur, nicht aber der Verkündiger, der die Literatur gerade berichtet hat.
Wist ihr woran das liegen könnte? Ich hoffe ihr versteht was ich meine. 🙂

**Comment by MarvinZeising** [comment]
Hallo Aaron,
könntest du deine Situation etwas genauer schildern?
Wo sehen die Verkündiger die berichtete Literatur nicht? Beim Hinzufügen der Publikationen schon? Oder erst wenn sie den Tab verlassen und dann wieder einschalten? Oder wenn sie das Berichtspopup abbrechen/erfolgreich beenden und es dann wieder öffnen?
Wo siehst du die Literatur? Wenn du ihr Berichtspopup öffnest? Oder im CSV-Export der Berichte?

**Comment by Aaron-Gruber** [comment]
Hallo Marvin,
vielen Dank schon einmal für deine Hilfe.

Einige Brüder sehen schon beim Hinzufügen der Publikation diese nicht. Sie klicken also, nachdem sie das Traktat, die Sprache und die Anzahl eingegeben haben, auf den "Plus" Button und sehen daraufhin die eben berichtete Publikation in der Übersicht nicht. 
Auch nachdem sie das Berichtspopup wieder öffnen oder den Tab wechseln wird die eben hinzugefügte Publikation nicht angezeigt.

Ich als Admin sehe allerdings alle Publikationen nachdem ich das Berichtspopup öffne. Auch im CSV-Export ist alles korrekt hinterlegt.

Würde es schon helfen, wenn einfach ein andere Browser verwendet wird? Mit Chrome sollte es doch in der Regel am besten funktionieren, oder? Gemäß meiner Einschätzung verwenden die meisten Brüder, die das beschriebene Problem haben, Safari.

**Comment by MarcBoettinger** [comment]
Hallo Marvin,

ich habe dasselbe Problem. Es betrifft Nutzer mit IOS. Gestern haben wir es auf zwei IOS Geräten ausprobiert. Im Prinzip kann die Literatur, zB WT / EW ausgewählt werden, eine Sprache, eine Stückzahl, aber wenn man auf das + drückt wird nichts hinzugefügt. In dem Depot sind über 60 WT / EWs angegeben.

Daneben kann bei dem Trolleyzustand nur "schlecht" eingegeben werden, wenn man auf "Gut" klickt springt es sofort wieder zurück. Auich das betrifft Nutzer mit IOS.

Gruss Marc

**Comment by MarvinZeising** [comment]
Danke für das Melden dieses Bugs!
Ich werde das Update morgen früh aufspielen.

**Comment by Aaron-Gruber** [comment]
Hallo Marvin, 

super. Vielen Dank für eure Arbeit.
Freu mich schon auf das Update. 

Liebe Grüße
Aaron
