### ISSUE TITLE
Teamleiter Manuell bestimmen

### ISSUE THREAD

**Issue by Aaron-Gruber** [JWDeveloper/JWManagement#164]
Uns ist aufgefallen, dass beim Manuellen hinzufügen von Verkündigern kein Teamleiter hinterlegt wird. Können Teamleiter auch Manuell bestimmt werden?

**Comment by mh166** [comment]
Das können sie. Hat für mich auch eine Weile gedauert, das herauszufinden. Aber so gehts:

![Teamleiter manuell setzen](https://user-images.githubusercontent.com/3167596/30762027-a07b4d64-9fe0-11e7-8a99-6ce0f1565911.png)

Die verfügbaren Teamleiter werden fett hervorgehoben. Klickst du jetzt auf den Stern hinten, wird der gewählte Verkündiger als TL gesetzt und rutscht in die erste Zeile hoch.

![Teamleiter gesetzt - neuer kann gewählt werden](https://user-images.githubusercontent.com/3167596/30762288-c3e62c46-9fe1-11e7-8655-c59a98816679.png)

Der Stern bei dem gewählten TL verschwindet und er wird nun unterstrichen hervorgehoben. Solltest du es dir nochmal anders überlegen, kannst du das mit dem Stern bei dem anderen Verkündiger anpassen.

**Comment by Aaron-Gruber** [comment]
Super. Danke. Die Funktion ist echt hilfreich.

**Comment by MarvinZeising** [comment]
Super Erklärung! Vielen Dank @mh166
