### ISSUE TITLE
manuell neue Verkündiger anlegen

### ISSUE THREAD

**Issue by Peter-Oberhausaen** [JWDeveloper/JWManagement#165]
Bei der manuellen Neuanlage wird von einem bereits angelegten User nicht automatisch angezeigt das dieser User bereits existiert.  Welche Tastenkombination kann ich nach Eingabe der Mail Adresse nehmen, damit ich dies überprüfen kann?

**Comment by mh166** [comment]
@Peter-Oberhausaen Hat sich deine Frage geklärt? Oder hast du aus Versehen das Issue abgeschlossen?

**Comment by Peter-Oberhausaen** [comment]
Ich habe das Issue irrtümlich gelöscht, aber gleich ein neues erstellt. Ich habe aber gesehen, dass der nächste User im Prinzip das gleiche Problem hat.
