### ISSUE TITLE
Neue Verkündiger manuell anlegen 

### ISSUE THREAD

**Issue by Peter-Oberhausaen** [JWDeveloper/JWManagement#166]
Nach der Eingabe der Mail Adresse wird der Verkündiger nicht automatisch erkannt, obwohl der Datensatz bereits existiert. Welche Tastenkombination kann nehmen, damit das Programm dies überprüft?

**Comment by MarvinZeising** [comment]
Same as #167 and #165 

Das genannte Verhalten beschreibt eine Änderung, die für die Anlage von neuen Benutzerkonten eingeführt wurde.
Dabei wurde die Verantwortung, bereits bestehende Accounts für weitere Projekte zu verwenden, den Projektkoordinatoren genommen und dem individuellen Benutzer gegeben.
Sobald ein Verkündiger dem Link aus der Einladungsmail folgt, kann er auf der sich öffnenden Seite entscheiden, ob er einen neuen Account anlegen möchte oder bereits einen Account hat. In letzterem Fall wird der temporär für ihn angelegte Account vom System wieder gelöscht und stattdessen der angegebene Account auf das neue Projekt berechtigt.
Falls ein Benutzer den neuen Account frei schaltet obwohl er bereits einen bestehenden Account hat, so kann er beide Accounts nachträglich im Profil zusammenführen.
Dort besteht die Möglichkeit, über den Button unten links, die Anmeldedaten eines zweiten Accounts einzugeben um die Berechtigungen des aktuellen Accounts auf den zweiten zu übertragen.
