### ISSUE TITLE
Vorhandene Accounts beim Anlegen neuer Nutzer nicht sichtbar 

### ISSUE THREAD

**Issue by jefffabian** [JWDeveloper/JWManagement#167]
Hallo, bisher sah man beim Anlegen neuer Benutzer direkt die bereits vorhandenen Accounts, sofern dieselbe Email-Adresse eingegeben wird. Dies ist nun nicht mehr der Fall, wodurch ein Administrator eines Projekts keine Accounts mehr zusammenfügen kann, bzw. bei einem vorhandenen Account keine Rechte eines neuen Projekts hinzufügen kann. Wird die Funktion wiederhergestellt? Lieben Dank

**Comment by Peter-Oberhausaen** [comment]
Das ist das gleiche Problem wie bei #166

**Comment by MarvinZeising** [comment]
Closed in favour of #166
