### ISSUE TITLE
Schichten laden verzögert

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#17]
Beim Laden der Schichten werden zuerst die Dummy Bilder eingeblendet.
Ich hatte jetzt den Fall das die Dummy Bilder 10 Sekunden blieben bis die Schichten geladen wurden.
Wenn sich 10 Sekunden lang nichts bewegt kann der Benutzer schnell denken da ist was kaputt.
Ein Vorschlag wäre einen bewegenden Lade Kreis auf die Dummy Bilder zu setzen.
Das klinkt zwar trivial, aber solange sich beim Laden etwas bewegt hat der Benutzer das Gefühl das die Seite nicht eingeschlafen ist.

**Comment by MarvinZeising** [comment]
Gute Idee.

Bei 10 Sekunden vermute ich mal nen Socket Reconnect für die Zeit, aber prinzipiell ist die Schichtseite sowieso nicht die schnellste. Könnte nochmal schauen, ob sich da nicht was rausholen lässt.

**Comment by MarvinZeising** [comment]
Habe mich jetzt schlussendlich dagegen entschieden.
Wenn alles gut läuft, laden die Schichten eigentlich schnell genug.
Wenn wirklich mal die Verbindung unterbrochen wird, wären Ladeanimationen irreführend, da der User die Seite dann doch lieber neu laden sollte.
Gleiches gilt für den Socket Reconnect (kann auftreten, wenn man nach längerer Inaktivität wieder mit der Seite interagiert, der Socket jedoch bereits vom Browser geschlossen wurde): Neu laden ist in diesem Fall sowieso schneller.
