### ISSUE TITLE
Seitenansicht im Splitview bei iPads

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#176]
Hallo,
Wenn man den Browser im Split View einstellt, geht die Seitenansicht der ganzen Woche (Quer) in die Ansicht wie beim Smartphone (Längs), obwohl noch viel Platz da ist.

**Comment by kepano75** [comment]
Ebenso wenn mehrere Apps im Split View angezeigt werden

**Comment by kepano75** [comment]
![6402b17a-d00d-40c6-9257-f5a031958d4e](https://user-images.githubusercontent.com/24876980/32988695-76d37b66-cd09-11e7-93cf-55828f487baa.png)
![bebeec04-9c70-40de-baba-8994d1581a91](https://user-images.githubusercontent.com/24876980/32988696-76edf1f8-cd09-11e7-8d55-d25817388a7b.png)

**Comment by kepano75** [comment]
Bilder vom iPad Pro 12"

**Comment by MarvinZeising** [comment]
In der Split-Ansicht ist leider denke ich immernoch nicht genug Platz, um Namen ordentlich anzuzeigen. Sonst würden von jedem Namen im unglücklichsten Fall nur 3,4 Buchstaben angezeigt werden - und das machts ja auch nicht wirklich besser.
Namen gar nicht anzuzeigen find ich dann auch schade. Dann kann man auch die Kalender Ansicht nehmen.
Von da aus fällt mir keine bessere Lösung ein, als wie es aktuell ist.
