### ISSUE TITLE
Neue Woche anlegen an den Kopf der Liste setzen

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#18]
Ich habe von Januar bis Juli die Wochen angelegt.
Um eine neue Woche anlegen zu können muss ich jetzt weit nach unten scrollen.
Mein Vorschlag wäre die "Neue Woche anlegen" Funktion an den Kopf der Liste zu setzen.

**Comment by MarvinZeising** [comment]
Diesen Button braucht man nicht oft. Theoretisch soll die Reise ja auch sowieso Richtung Automation gehen, so dass niemand mehr manuell Wochen anlegen muss.
Davon abgesehen: Wenn ich eine neue Woche anlegen möchte, wird das mit der höchsten Wahrscheinlichkeit einfach die nächste Woche in der Reihenfolge sein. Also die, die auf die letzte Woche der Dropdown-Liste folgt.
Somit spiegelt der "Neue Woche anlegen" Button quasi schon genau diese neue Woche wieder.
Daher halte ich ihn dort für ganz gut platziert.

**Comment by schillermann** [comment]
Unter dem Gesichtspunkt hast du recht.
