### ISSUE TITLE
Teamleiter/Ersatz-Teamleiter

### ISSUE THREAD

**Issue by ChristianTemborius** [JWDeveloper/JWManagement#180]
**Bei Bewerbung eines _"Teamleiter"_ und eines _"Ersatz-Teamleiter"_ sollte die Rolle _"Teamleiter"_ unabhängig vom Eingangszeitpunkt der Bewerbung vorrangig an den _"Teamleiter"_ vergeben werden.**

Zu Erklärung die aktuelle Situation:
- Zwei Schwestern bewerben sich für den Trolley-Dienst.
Beide haben die Rolle "Ersatz-Teamleiter" damit ein Schicht-Bericht abgegeben werden kann. Die Reihenfolge der Bewerbung hat somit nur einen indirekten Einfluss, welche Schwester den Bericht anfertigt.
- Zwei Brüder bewerben sich für den Trolley-Dienst.
Beide haben die  Rolle "Teamleiter". Die Reihenfolge der Bewerbung hat somit nur einen indirekten Einfluss, welcher Bruder den Bericht anfertigt.
- _Ein Bruder und eine Schwester bewerben sich für den Trolley-Dienst._
Der Bruder hat die Rolle "Teamleiter", die Schwester entsprechend die Rolle "Ersatz-Teamleiter". Je nach Reihenfolge des Eingangs der Bewerbung kommt es vor, dass die Schwester als Teamleiterin geführt wird und somit auch den Bericht eingeben soll. Dies muss jeweils vom "Schichteinteiler" oder "Administrator" manuell angepasst werden.

**Comment by MarvinZeising** [comment]
Lieber Christian,
sorry wegen der späten Antwort. Besteht das Problem immer noch?

**Comment by ChristianTemborius** [comment]
Hallo Marvin.
Keine Sorge wegen der späten Antwort. Andere Dinge haben manchmal Vorrang.

Das Problem besteht aktuell noch immer. Jeweils der letzte hinzugekommene
Teilnehmer mit Teamleiter/Ersatzteamleiter bekommt automatisch die Leitung
zugeteilt, obwohl sich womöglich vorher bereits ein Teilnehmer mit
"höherer" Qualifikation für das Team gemeldet hatte.

Gruß, Christian

Marvin Zeising <notifications@github.com> schrieb am Mi., 15. Aug. 2018,
19:27:
