### ISSUE TITLE
Messed up my Admin Account - Locked out

### ISSUE THREAD

**Issue by tyrone393** [JWDeveloper/JWManagement#182]
I am the administrator for the Southwest Congregation Cart Witnessing schedule.  I currently cannot login.  I accidently sent myself an invitation which has locked me out.  Can you reset my access?  Frederickcbrown@gmail.com. Fred Brown.

Thank you very much for your help.
Fred Brown

**Comment by jipsen3429** [comment]
Hello, I am also an admin for the Love Field English scheduling account. I also accidentally sent myself an invite which has locked me out of the admin login. Can you reset my account too?

Thank you,

Jonathan Ipsen

**Comment by MarvinZeising** [comment]
I created a new account for you @jipsen3429 
I'm closing this since problems like this should normally be reported via email to support@jwmanagement.org but not as an issue in GitHub.

**Comment by jipsen3429** [comment]
Understood – thank you for your help.
