### ISSUE TITLE
Schichtleiter/Schichtplaner

### ISSUE THREAD

**Issue by baerenstark** [JWDeveloper/JWManagement#183]
Hallo, seit vorgestern haben der Schichteinteiler  und Schichtplaner keinen Zugriff mehr auf den Button Verwaltung auf dr Übersichtseite. Die Button Infos und Scchichten funktionieren ganz normal.

**Comment by kepano75** [comment]
Bei unseren Projekt auch! Als Admin geht es... wieder

**Comment by MarvinZeising** [comment]
Bug sollte behoben sein.
