### ISSUE TITLE
Mail unterbesetzte Schicht

### ISSUE THREAD

**Issue by Peter-Oberhausaen** [JWDeveloper/JWManagement#184]
Hallo zusammen,

ich habe wahrscheinlich nur ein rein individuelles Problem. Ich empfange überhaupt keine Mails "Schicht unterbelegt" egal ob ich sie selbst veranlasse  oder jemand anders. Ich arbeite mit Chrome und die Mails bleiben nicht als Spam hängen. Ich habe auch ein weiteres Konto als normaler Nutzer, angelegt.   
Muss ich etwas an den Einstellungen ändern?

**Comment by MarvinZeising** [comment]
Lieber Peter,
du musst in deinem Profil den Haken bei "Ich darf kurzfristig kontaktiert werden" setzen, um diese Mails zu erhalten.
