### ISSUE TITLE
Request: Information Centre - sorting of questions, assigning to new tabs 

### ISSUE THREAD

**Issue by AdamMeyerJW** [JWDeveloper/JWManagement#185]
Hello,

Is it possible to re-sort questions in the information centre? At the moment, I need to delete and re-create them if I want to change the order in which the questions appear.

Likewise, is it possible to re-assign questions to a different tab?

Thanks in advance,
Adam

**Comment by MarvinZeising** [comment]
Hello Adam,
Thank you for suggesting this.
We'll likely re-do the information centre at some point in the future.
If it's not a big deal, I'll see what we can do.
Thanks,
Marvin

**Comment by muhkuhxy** [comment]
Reassigning questions to a new tab would be a more involved change, so for now we opted to just make them sortable per tab. I'll open a new issue for moving questions between tabs, but it may be a while before we come around to it. Hope this helps :)
