### ISSUE TITLE
Can't sign into account/Project anymore

### ISSUE THREAD

**Issue by doxendine** [JWDeveloper/JWManagement#187]
Hi. 
My account was created 2 days ago. After using for a couple days, I added a couple users. I then 'invited' the users to the account. When the box comes up to check which users you want to invite, I also checked myself (maybe I should not have done this). I then received an email telling me that 'JW Management Account Created!' After clicking 'Lets Go' it states, 'This link has expired'. And now I can't login to the account anymore. I also can't request a password reset. It says my email is not in the system. 
Any Thoughts?
Thanks, 
Congo: Cabo San Lucas
Login: doxendine

**Comment by MarvinZeising** [comment]
Hi @doxendine,
You're account was deleted somehow.
I created a new one for you and sent you the invitation.
Your brother,
Marvin
