### ISSUE TITLE
Pfeile zwischen den Schichten

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#19]
Haben die Pfeile zwischen den Schichten eine besondere Bedeutung?
Wozu sind sie da?
Meine erste Reaktion ist das ich drauf klicke weil ich erwate das sich was ausklappt.

**Comment by tim-antkowiak** [comment]
Die Pfeile sind nur ein Platzhalter, welche die nächste Schicht andeuten sollen. Sie haben also keine besondere Bedeutung sondern sind nur ein Designelement.

**Comment by schillermann** [comment]
Hab ich mir schon fast gedacht :-)
Versuche mich nur in jemand hinein zu versetzten der wenig geübt mit dem PC ist. Sollte für euch nur als Anregung dienen. Wenn man Pfeilen eine Funktion zuweist wie hier der Zurück Button oben Links, dann erwartet der Benutzer auch das der Pfeil zwischen den Schichten eine Funktion hat. Ist die Idee eines durchgängigen Design und Benutzerkonzept.

**Comment by tim-antkowiak** [comment]
Okay, danke für den Hinweis :-)
