### ISSUE TITLE
Can Not add a New Week

### ISSUE THREAD

**Issue by ksl64** [JWDeveloper/JWManagement#197]
JWManagment does not let to add new weeks, and the admin settings never loads.

**Comment by MarvinZeising** [comment]
Hello @ksl64,
which project do we speak about and what's your username?
Kind regards,
Marvin

**Comment by ksl64** [comment]
Hello @MarvinZeising
my username is kseda the project JWManagement

The issue was fix, aparently is was a temporali lag.
Thanks! 

Cordially,
Kenneth
