### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by pepekall** [JWDeveloper/JWManagement#198]
Hello,
it seems the Date and Calendar localization is not done with the translation files?
They remain in English when selecting language (i.e. Finnish)

Also the email about the new user is in English.

BR,
Juha

**Comment by MarvinZeising** [comment]
Hello Juha,
We will tackle this with the next update (which is currently available on [staging.jwmanagement.org](https://staging.jwmanagement.org)).
The email for new users is being sent in the language that you (the user that triggers the sending of these mails) have the website open, currently.
Your brother,
Marvin
