### ISSUE TITLE
Can't login to the site

### ISSUE THREAD

**Issue by pepekall** [JWDeveloper/JWManagement#199]
Hello,
there seems to be a problem on the site. No one can login and the shifts are not accessible.

BR,
Juha

**Comment by MarvinZeising** [comment]
Hey Juha,
This always happens when the server runs short on RAM. A few seconds/minutes later, the app is being restartet and everything should be working fine, again.
With the next update, we will try to conquer this with daily deployments.
Your brother,
Marvin
