### ISSUE TITLE
Zurück Button in der Projekt Auswahl fehlt

### ISSUE THREAD

**Issue by schillermann** [JWDeveloper/JWManagement#20]
Wenn ich auf Schichten klicke werden mir meine Projekte angezeigt.
Von hier aus habe ich keine Möglichkeit mehr zur vorherigen Seite zu kommen.
Erst wenn ich ein Projekt aus der Liste ausgewählt habe bekomme ich die Möglichkeit auf die Startseite zurück zu kehren.

**Comment by 51773ELLIS** [comment]
Indem Sie auf den unscharfen Hintergrund klicken, kehren Sie zu den Projekten zurück 
![1h0nf7](https://cloud.githubusercontent.com/assets/20007944/21614482/8b58c5c0-d1d1-11e6-86d2-be4562e7cd37.gif)

**Comment by schillermann** [comment]
Da wäre ich nie drauf gekommen :-)

**Comment by schillermann** [comment]
Wäre vielleicht mal ne Möglichkeit darüber nachzudenken oben links die Beschreibung Übersicht mit einem Pfeil als Zurück Button genutzt werden kann, so wie es auf der Schichtseite ist. Es ist sehr verwirrend wenn man auf unterschiedlicher weise immer zurück auf die vorherige Ansicht kommt. Eine andere Möglichkeit wäre ein x Button für das Schliessen der Projektliste anzuzeigen.

PS: Die App ist gerade down.

**Comment by schillermann** [comment]
Warum werden die Issues hier so in windeszeile geschlossen.
Man bekommt ja keine Zeit mehr zu Antworten.

**Comment by MarvinZeising** [comment]
Unser Wechsel auf GitHub ist zwei Tage her. Gib uns ein bisschen Zeit, um uns an die Dinge hier zu gewöhnen :-)

Also der Pfeil zurück macht keinen Sinn in Bezug auf "die Idee eines durchgängigen Designs und Benutzerkonzepts" (#19), denn der Link oben links führt immer auf eine andere Seite und immer in Richtung Übersichtsseite, vollbringt somit also einen kompletten Seitenwechsel.
Das Öffnen der Tag-Übersicht dagegen (also sobald man auf Schichten klickt) ist lediglich eine Interaktion mit einem Teil der Seite. Ein Rücksprung bzw. ein Schließ-Mechanismus müsste dementsprechend auch nur für diesen Teil der Seite erfolgen und nicht für die gesamte Seite, wie das der Pfeil oben links zeigen würde.
Und selbst wenn, kann man auf der Übersichtsseite selbst logischerweise nicht mehr zurück, denn man ist ja schon am Ende angelangt. Somit wäre das irreführende Benutzerführung.

Dennoch haben uns natürlich überlegt, ob ein Schließen-Button in einer der Ecken des unscharfen Fensters eine gute Option wäre. Allerdings haben uns dagegen entschieden, um das gleiche Prinzip anzuwenden, das auch bei den Modals und SweetAlerts zutrifft. Nämlich dass man Selbige mit einem Klick auf den leicht ausgeblendeten Hintergrund drumherum schließen kann.
In diesem Fall ist es halt kein ausgegrauter, sondern ein unscharfer Hintergrund.
Gerade auf mobilen Geräten halten wir das für eine intuitive Reaktion.

**Comment by schillermann** [comment]
Sehr gut überlegt und durchdacht.
Weiter so.
