### ISSUE TITLE
Löschen aller Schichten je Wochentag in Vorlagenwoche funktioniert nicht

### ISSUE THREAD

**Issue by PPdev** [JWDeveloper/JWManagement#201]
Der Button "Alle löschen" je Wochentag in einer Vorlagenwoche funktioniert nicht. 
Das liegt daran, dass nach dem GET-Parameter _showTags_ gesucht wird, der Tag aber nur in _tagId_ steht.

**Workaround:** an die URL `&showTags=[TAGID]` dranhängen.

**Comment by MarvinZeising** [comment]
Wow, gut herausgefunden!
Tut mir leid, wenn ich das nicht mehr fixen werde.
Ich werde versuchen, die Schichten Seite in nächster Zeit komplett mit dem Kalender und anderen Funktionen zu ersetzen.
Dann wird es showTags und tagId beides nicht mehr als URL-Parameter geben.

**Comment by MarvinZeising** [comment]
Sorry, war eigentlich alles andere als schwer das zu fixen.
