### ISSUE TITLE
Kopierte Vorlagen übernehmen die TAGS nicht korrekt

### ISSUE THREAD

**Issue by Daniel-vhm** [JWDeveloper/JWManagement#202]
Wenn ich eine Vorlage erzeuge und das "Entsprechende" auf andere Tage kopiere, dann wird beim Ausfüllen einer Woche mit den Mustervorlagen nicht der richtige Tag eingetragen.
In der Schicht-Ansicht sieht man das nicht, wohl aber in der Kalenderansicht!!!
Außerdem ist es in den Berechtigungen zu bemerken!

Ich habe eine "allgemeine Vorlage" in einem separaten "TAG" erzeugt.
Manchmal wird er TAG der angelegten Schichten beim kopieren mit dem TAG der Vorlage ersetzt...
Aber nicht immer... Wenn man die einzelnen "kopierten" Schichten nochmals auswählt und den korrekten TAG, der bereits drinsteht, NOCHMAL auswählt, dann wird es korrekt gespeichert und es gibt auch keine Probleme in der Kalenderansicht und mit den Berechtigungen...

**Comment by MarvinZeising** [comment]
Gut herausgefunden!
Aktuell wird beim Kopieren immer das Tag eingetragen, zu dem die Vorlage gehört.
Ich werde das anpassen.
Vielen Dank,
Marvin
