### ISSUE TITLE
Upload CSV-File

### ISSUE THREAD

**Issue by donwence** [JWDeveloper/JWManagement#203]
Have tried many combinations of csv file format (UTF-8, commas, semi-colons, quotes, no quotes, double quotes, header, no header) and all get this error:

Error false File format
File has to be a CSV-File

Is there anything else I may be missing?

Thank you for the well thought out application.

Don

**Comment by PPdev** [comment]
Hi Don,

you're speaking of the user import, right?
A convenient way to get a working CSV file, is to export the existing user(s), open the downloaded CSV file and append your data to it (e. g. in MS Excel or a text editor).

Best regards
Pascal

**Comment by donwence** [comment]
Thank you for the quick reply Pascal.  Yes, we would like to import our list of participants.  Thank you for the suggestion.  I've now tried by adding a single user and by not changing the users.csv.  Attempted imports of both return the same False File error.

Don

**Comment by donwence** [comment]
I've now tried in Edge and Chrome.  I'm sorry, it must be something simple I'm doing.

Don

**Comment by MarvinZeising** [comment]
Hey Don,
if the problem still persists, please send the csv file to support@jwmanagement.org. Then I'll have a look and see if I find anything that's not as it's supposed to be.

**Comment by MarvinZeising** [comment]
Closing this for now
