### ISSUE TITLE
Es werden keine E-Mails über "Team absagen" versendet

### ISSUE THREAD

**Issue by kevin-richter** [JWDeveloper/JWManagement#204]
Falls eine Schicht über den Button "Team absagen" abgesagt wird, dann erscheint ein Fenster, in dem man den Grund der Absage eintragen kann. Diese Angaben sollen dann an alle Teilnehmer der Schicht per E-Mail versendet werden. Das funktioniert aber nicht. Die Teilnehmer erhalten keine E-Mails.

Zusätzlich wäre es praktisch, wenn auch die E-Mail-Adresse des Projekts diese Absage-Mail empfangen könnte. Da auch Teamleiter ihre Schichten über diesen Button absagen können, würden so automatisch auch die Admins des Projekts über die Absage und den Grund informiert werden.

Vielleicht könnte bei einer so abgesagten Schicht auch die Dienstzeit im Schichtbericht automatisch auf "00:00" gesetzt werden. Das erleichtert die Erstellung von Statistiken über die Tabelle "reports".

**Comment by MarvinZeising** [comment]
Lieber Kevin,
die Absage-Mails gehen nur an die Verkündiger raus, die vorher auch über ihre Zuteilung informiert wurden. Das Papierflieger-Symbol muss also blau gefüllt sein.

Die E-Mail an die Projekt E-Mail Adresse zu schicken ist eigentlich gar keine schlechte Idee. Vielleicht wäre dann nur eine Einstellungsmöglichkeit wichtig, ob diese Mails dorthin geschickt werden sollen oder nicht.

Die Dienstzeit herunter zu setzen macht Sinn. Darum werde ich mich kümmern.

**Comment by kevin-richter** [comment]
Vielen Dank für das Lösen dieses Problems und das Einpflegen der Verbesserungen.

Ein Punkt ist aber noch offen:
Könnte die Team-abgesagt-Mail nicht nur an die Verkündiger der jeweiligen Schicht, sondern auch an die E-Mail-Adresse des Projekts versendet werden? Da auch Teamleiter ihre Schichten über diesen Button "Cancel team" absagen können, würden so automatisch auch die Admins über die Absage und den Grund informiert werden.
