### ISSUE TITLE
Verwaltung/Berichte funktioniert nicht richtig

### ISSUE THREAD

**Issue by Georgios01** [JWDeveloper/JWManagement#205]
Hallo,
ich hätte eine Frage bezüglich den Berichten:
Wenn jemand nach einer Schicht den Bericht abgibt, werden z.B. die Gespräche und die Abgaben unter der Verwaltung/Berichte nicht angezeigt. Es ist alles nur 0.
Nur die Teilnehmer werden angezeigt.
Darüber hinaus wenn ich den Bericht als csv Datei herunterladen möchte, funktioniert das auch nicht.

Danke im voraus für Eure Antwort.

**Comment by MarvinZeising** [comment]
Lieber Georgios,
die Zahlen, die auf der Berichte-Seite angezeigt werden, sind nicht wirklich ernst zu nehmen.
Die Seite wurde leider nie fertig.
Aber der CSV-Export sollte eigentlich klappen, insofern du den richtigen Monat auswählst.
Dass das nicht klappt, wundert mich. Was genau passiert denn? Und welchen Browser benutzt du?
