### ISSUE TITLE
Minimization of clicks

### ISSUE THREAD

**Issue by josuavogel** [JWDeveloper/JWManagement#207]
During the daily use, it turned out to me, that theoretically one navigation step could be saved. Theoretically, a click on "Schichten" could open the view with all (in this view you can already filter by tags). This would eliminate the need for a popup. In 98% of all cases, I would like to have a complete overview. I find the popup on mobile screens rather disturbing.

This is not an important feature, but nice to have.

**Comment by MarvinZeising** [comment]
Hey Josua,
Thank you for this suggestion.
With the next update, this "popup" will be eliminated.
Unfortunately, though, it will also introduce a new project overview page.
Therefore, the number of clicks remains the same.
But at least we have a clearer separation of projects now for all the publishers that have access to multiple projects (the number of these is increasing drastically).
I'm going to close this as it's kind of done.
