### ISSUE TITLE
Erstanmeldung nach Einladung per Mail

### ISSUE THREAD

**Issue by Rothammel** [JWDeveloper/JWManagement#208]
Hallo,
bei der Erstanmeldung nach Email Einladung ist der Benutzername schon belegt, wenn man vergisst die Nutzungsbedingungen und Datenschutz abzuchecken.
Viele Grüße
Stan

**Comment by MarvinZeising** [comment]
Hallo Stan,
ich habe das gerade mal getestet und es funktioniert bei mir einwandfrei.
Ich habe es mit Chrome und IE getestet, welchen Browser verwendest du denn?

**Comment by Rothammel** [comment]
Hy, es war Chrome 68.0.3440.91 auf einem Samsung S5 (SM-G900F) mit LineageOS 14.1-20180513.
ich habe das jetzt auch reproduzieren wollen und es gab mit einem neuen Benutzernamen keine Probleme. kann ich mir die zugeordneten Benutzernamen anzeigen lassen?

**Comment by MarvinZeising** [comment]
Danke für die Infos.
Den Benutzernamen kannst du in deinem Profil einsehen (https://www.jwmanagement.org/de/profile).

**Comment by Rothammel** [comment]
gut dann habe ich soeben raus gefunden, ein Benutzername 'test' ist belegt. es befindet sich außer meinem Benutzer nur noch der support admin in der Liste.

**Comment by MarvinZeising** [comment]
In der Liste siehst du nur die Accounts, die Zugriff auf dein Projekt haben.
Benutzernamen gelten allerdings über Projekt-Grenzen hinaus.
Und bei über 22.000 Accounts wird wohl der eine oder andere Benutzername schon belegt sein.

**Comment by Rothammel** [comment]
mit dem Wissen hat sich der issue erledigt ;-) sorry für die Inanspruchnahme deiner Zeit

**Comment by MarvinZeising** [comment]
Kein Problem :-)

**Comment by Rothammel** [comment]
Welchen Sinn hat denn dann ein Username? Ist er nicht obsolet, wenn doch die E-Mail unique ist und zum (einmaligen) login verwendet werden würde.

**Comment by MarvinZeising** [comment]
Die E-Mail Adresse ist nicht unique. Der username schon.
Deshalb kann z.B. ein älteres Ehepaar, das nur eine gemeinsame Adresse hat, dennoch zwei Accounts haben - einen für jeden.
Rein theoretisch könnte man aber natürlich einbauen, dass er auch die E-Mail Adresse zum Anmelden akzeptiert, insofern es nur einen Account mit dieser E-Mail Adresse gibt.

**Comment by Rothammel** [comment]
Aha
