### ISSUE TITLE
Hello, I tried to invite new users, I selected all that I wanted invited and it didn’t do anything. I tried one at a time and still nothing. I was able to do for some reason two sisters, but no more. 

### ISSUE THREAD

**Issue by wesblair** [JWDeveloper/JWManagement#215]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wesblair** [comment]
I tried sending an invitation to all the new publishers. The email only went to one. I have been able to invite one other sister so far, other than that everyone else doesn’t seem to working. I was wondering if there is a bug in the invitation part of the program. Or maybe I’m doing something wrong. It seems simple to use.

**Comment by wesblair** [comment]
Tried using windows 10 on my laptop and iPad with iOS 11.4. Can not send invitations to new users.

**Comment by wesblair** [comment]
Using safari and google chrome.

**Comment by wesblair** [comment]
Sorry, looks like it’s working.

**Comment by MarvinZeising** [comment]
Okay good to hear it's working

**Comment by wesblair** [comment]
Thank you. I realized for some the invite was going to there junk box. But it’s working.
This is an awesome program.
Thank you for developing it and maintaining it, it’s a huge help for brothers who have to schedule the public Witnessing.

Wes Francis

On Sep 14, 2018, at 7:42 AM, Marvin Zeising <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #215<https://github.com/JWDeveloper/JWManagement/issues/215>.
