### ISSUE TITLE
Funktion "markieren" von Schichten

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#22]
Die alte Funktion, eine Schicht zu markieren und manuell die VK über einen kurzfristigen Ausfall per Email zu informieren sollte wieder implementiert werden.
Wenn möglich sollten bei einem fehlenden TL  auch nur die angeschrieben werden, die die Rolle TL eingetragen bekommen haben.

**Comment by tim-antkowiak** [comment]
Eigentlich hatten wir das so implementiert, dass wenn ein Teamleiter fehlt, auch nur Teamleiter angeschrieben werden.
Die Funktion schaut, ob es unter den zugeteilten Verkündigern noch einen Teamleiter gibt und sollte, wenn dies nicht der Fall ist, auch nur an Teamleiter eine E-Mail schicken.

**Comment by alisander2** [comment]
Hallo Tim,
dann ist das ja super!
Es sollte aber nicht sofort die Email raus, dass die Schicht abgesagt werden würde. Das sollte nur am Vorabend, so gegen 23:30 erfolgen. Gerade bei großen Trolleyprojekten kommen immer noch kurzfristig Anmeldungen rein. 
Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Tue, Jan 3, 2017 at 7:02 PM +0100, "Tim Antkowiak" <notifications@github.com> wrote:












Eigentlich hatten wir das so implementiert, dass wenn ein Teamleiter fehlt, auch nur Teamleiter angeschrieben werden.

Die Funktion schaut, ob es unter den zugeteilten Verkündigern noch einen Teamleiter gibt und sollte, wenn dies nicht der Fall ist, auch nur an Teamleiter eine E-Mail schicken.

**Comment by MarvinZeising** [comment]
Da der eigentliche Zweck hier erfüllt wurde, schließe ich das mal.
