### ISSUE TITLE
Since latest design update the website is extremely slow

### ISSUE THREAD

**Issue by MarcBoettinger** [JWDeveloper/JWManagement#271]
For me it takes several minutes to load one page since the latest design update. Expecially displaying the shifts takes one to two minutes.  This is independent whether I display the page on my smartphone or on Chrome on an Windows 10 PC.

**Comment by 3djevon** [comment]
Our publishers are experiencing the same issues.

**Comment by MarvinZeising** [comment]
Server is back up now. Running on enough containers to cope with the over 300 simultaneous connections. Sorry for any inconveniences
