### ISSUE TITLE
Project news can't be edited

### ISSUE THREAD

**Issue by wesblair** [JWDeveloper/JWManagement#275]
I’m not sure if this is a bug. But since the dashboard change I can’t see how to change my note that shows up on the top of the dash board. I have been using this to communicate with the participants. Thank you for all your work.

**Comment by MarvinZeising** [comment]
Thanks for posting this issue.
The news still have to be edited via the old dashboard.
But we'll migrate that to the new dashboard, too.

**Comment by pungggi** [comment]
Hi @MarvinZeising I am working on this.
Could check this feature branch for some feedback.. I still need to find a hack to span to 100%..
Any adivce is much appreciated.
https://github.com/JWDeveloper/JWManagement/tree/Project-news-%23275

**Comment by MarvinZeising** [comment]
Hey @pungggi,
Awesome work! Thank you :-)

I think you could add a ```width: 100%``` to the ```_settings.scss``` file.

![image](https://user-images.githubusercontent.com/12305625/50820885-21eb4180-132e-11e9-8b50-64b8a3496059.png)

**Comment by pungggi** [comment]
Thank you that helped!
