### ISSUE TITLE
Fail more gracefully on old versions of Chrome

### ISSUE THREAD

**Issue by ssb22** [JWDeveloper/JWManagement#276]
The client-side Javascript uses [ES6 default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) (e.g. `lang_tag = null`), a syntax which is [not supported in Chrome 48 or below](https://www.chromestatus.com/feature/5275456790069248) (it requires Chrome 49).  People still suck using pre-10.9 Macs [stopped receiving Chrome updates in April 2016](https://chrome.googleblog.com/2015/11/updates-to-chrome-platform-support.html), so the last version they could get is 49 (which supports the syntax), but if they didn't accept the update in March 2016 (or if they're using [Chromium](https://www.chromium.org/Home) which I think didn't push one) then they will now have 48 until they [manually install Chrome 49](https://www.slimjet.com/chrome/google-chrome-old-version.php) (or [Chromium 49](https://sourceforge.net/projects/osxportableapps/files/Chromium/)).

On Chromium 48 the start page is blank (with syntax errors in the developer console).  It would be nice to have a "your browser is not supported, here's how to upgrade" message instead of a completely blank page.  Perhaps a separate `<script>` can run first, that checks `navigator.userAgent` and does a simple `document.write` to warn if it's Chrome 48 or below?

Chrome 49 is currently working OK.

**Comment by MarvinZeising** [comment]
That is one amazingly detailed bug description! Thank you!

**Comment by ssb22** [comment]
Old versions of Safari are also affected: [anything below Safari 10](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/default_parameters#Browser_compatibility) won't support default parameters and will just syntax-error on a blank page.  To check for this in `navigator.userAgent`, you need to check for `Safari` and beware of `Version/9.0` or below.  This affects devices like the [iPad 2](https://en.wikipedia.org/wiki/IPad_2), as the last OS update Apple pushed to it is iOS 9 with Safari 9 (iOS 10 is not available).

**Comment by ssb22** [comment]
The "Amazon Silk" browser on the "Kindle Fire" phone might also be affected.  Silk's current documentation [implies it's on Chrome 44](https://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html) which is below 49.  We have a report of the site being non-loadable on Silk, but I have not confirmed that this is the same problem. But it seems likely. I suggest using the above script to directly probe for the issue, instead of relying on a `navigator.userAgent` test, since we do not have an exhaustive list of affected browsers that people still use.

**Comment by ssb22** [comment]
Found the root cause of this general incompatibility with old browsers: the commit on Wed Oct 10 16:57 "pin coffeescript to version 2".

As mentioned in the [CoffeScript 2 release announcement](https://coffeescript.org/announcing-coffeescript-2/), CoffeeScript started emitting "ultra-modern" Javascript in version 2, and suggested we use a transpiler like [Babel](https://babeljs.io/) if we still want our code to work in older browsers.

So now we have a choice:
* back off to version 1.x of CoffeeScript, or
* start using a transpiler like Babel to post-process the JS it generates, or
* declare that support for old browsers has dropped (but it would be nice to add the JS snippet above, so that people running such browers know what has happened and are not just presented with a blank screen).

**Comment by MarvinZeising** [comment]
All this stuff is due to ES6 features and - what it seems like - not-working babel anymore.
I have to figure out if this has to with Meteor 1.8 (I'm quite sure) and/or Galaxy. Maybe a configuration is needed to address older browsers, too.

**Comment by MarvinZeising** [comment]
The update is finally deployed :-D
Older devices and browser should now be able to visit the page, again.
Sorry for the delay and any inconveniences.
