### ISSUE TITLE
Placeholders in shift assignment mail are not replaced

### ISSUE THREAD

**Issue by PPdev** [JWDeveloper/JWManagement#293]
**Describe the bug**
The mail body of the shift assignment mail still contains the placeholder keys (in my case: mail, hello, text1). Nevertheless the values are inserted after the placeholder keys correctly. 

**To Reproduce**
Apply for a shift, open mail.

**Expected behavior**
The values should replace the placeholders.

**Desktop:**
Browser: Chrome 69.0.3497.100

**Comment by MarvinZeising** [comment]
This should be fixed by 1c2981d3f71d96dc3263a4a68f28a01ec6e85094, now.
Thanks for reporting this and especially for the detailed description and repro steps!
