### ISSUE TITLE
User account is deleted somehow

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#294]
Had a project coordinator whose account was deleted somehow although he participated in 4 projects.
AFAIK he forgot his password and got it reset by someone else.
After that, his account was removed completely.

**Comment by MarcBoettinger** [comment]
I got a similar issue. One user could login but was not able to participate in our project. So I guessed that he occasionally clicked on "leave project". I deleted the account and did set him up again and he was able to see the project.

Two days later same issue. The user is technically very affine so I guess it cannot be that he pressed "leave project" twice.

Very strange.

Marc.

**Comment by MarvinZeising** [comment]
Thanks for the example.

Just a quick question: How could you delete the account if the user didn't have access to the project?

If he is visible in the publishers list of your project, he should be able to see the shifts and such (given he has permissions set for one or more tags).

**Comment by MarcBoettinger** [comment]
He was not visible for me in the publishers list, so he deleted the account himself.

After we recreated the account he was visible and he was able to see the project but he now gets an error 550 saying he is not participating in the current tag.

Marc

**Comment by MarcBoettinger** [comment]
Update: checking the user account he got the right tag.

**Comment by MarcBoettinger** [comment]
Another update: his role was missing. I guess it shoukd work now.

**Comment by MarvinZeising** [comment]
Okay, good to hear that you were able to resolve the issue :-)
