### ISSUE TITLE
The login page is not displayed

### ISSUE THREAD

**Issue by hervengassop** [JWDeveloper/JWManagement#301]
Windows 8 64-bit

![bug](https://user-images.githubusercontent.com/12395887/47813251-cce9e880-dd4a-11e8-88b8-64fe0b323f43.png)

**Comment by MarvinZeising** [comment]
Do you have AdBlock or some similar extension installed, maybe?
If so, does disabling this extension for jwmanagement.org help?

**Comment by hervengassop** [comment]
Interesting!
Yes, i've disabled all similar extensions like AdBlock: the view is yet available.
Thanks.
