### ISSUE TITLE
beamerSelector gets in the way of Close button in iPhone popup

### ISSUE THREAD

**Issue by ywc29** [JWDeveloper/JWManagement#310]
As shown on the attached screenshot, the notification icon (which has DOM ID beamerSelector) can hover over the Close button.  This is on an iPhone 6S running the default Safari browser in iOS 11. 
![screenshot](https://user-images.githubusercontent.com/38359549/47966748-fdcd6480-e04d-11e8-8e19-5107132df105.jpg)
Perhaps this could be worked around by moving the Close button, or by providing some way to make that notification icon disappear?

**Comment by ssb22** [comment]
I'm afraid that fix was not complete, Wendy is still having trouble on other popups as shown in this screenshot:
![image](https://user-images.githubusercontent.com/2261921/47995328-d9749500-e0ec-11e8-978c-4474530c0fff.png)
