### ISSUE TITLE
User Popover is lost when displayed on smaller screens. i.e. Mobile devices / Tablets 

### ISSUE THREAD

**Issue by 51773ELLIS** [JWDeveloper/JWManagement#32]
![screen shot 2017-01-05 at 11 38 40](https://cloud.githubusercontent.com/assets/20007944/21679364/a6cfed90-d33b-11e6-9191-54226066ad68.png)
 <h3>As seen here the pop over is cut in half when out of screen border.</h3>

**Comment by MarvinZeising** [comment]
Closing this in favor of #33
