### ISSUE TITLE
Anzeige für Teilnehmer

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#35]
Vielleicht mache ich was falsch.
Ich möchte, dass die Schichten min. mit drei und höchstes mit 4 besetzt sind.
Jetzt habe ich es in der Vorlage so konfiguriert und für Februar die neuen Schichten angelegt.

Jetzt kann ich als Admin sehen, wer drin ist. 

Die Teilnehmer sehen aber nicht wer drin ist, sie sehen nur, dass die Schicht orange ist.

Die Verkündiger möchten ja schon gern sehen wer dort drin ist, oder haben sich verabredet. Das war vorher einfach.
Oder ich mache einfach etwas falsch. :-)

**Comment by MarvinZeising** [comment]
Scheint mir tatsächlich ein bug zu sein.
Bei "sofort annehmen" Schichten sollten Bewerber für die Verkündiger sichtbar sein.

**Comment by MarvinZeising** [comment]
Der Fix geht mit Release 1.0.3 live
