### ISSUE TITLE
some public routes don't work

### ISSUE THREAD

**Issue by muhkuhxy** [JWDeveloper/JWManagement#350]
for example https://www.jwmanagement.org/privacy

doesn't work locally either

![image](https://user-images.githubusercontent.com/3495210/49961573-4f052980-ff13-11e8-9a70-fc2d717a1cdb.png)

**Comment by muhkuhxy** [comment]
i think it may be because the `/:projectId` matches these routes

**Comment by MarvinZeising** [comment]
Good find, thanks :-)
Made it work again.
It is now available under /de/privacy because it's german-only
