### ISSUE TITLE
auto-reload nach Schichtbewerbung

### ISSUE THREAD

**Issue by aui01** [JWDeveloper/JWManagement#351]
Ein Verkündiger bewirbt sich für eine Schicht, schließt dann das Popup und ist zurück in der Kalenderansicht. Könnte man beim Schließen des “Bewerbungsfensters” die Kalenderansicht neu laden, damit der Verkündiger dort seine gerade abgegebene Bewerbung schon sieht? 

 Aktuell sieht man in dem Kalender nicht, was man gerade getan hat. 
Danke vorab. 
![d8aad262-c9d1-4acd-a8b6-ad477ac60581](https://user-images.githubusercontent.com/45858543/49962659-11ee6680-ff16-11e8-8b20-96b9071207e5.jpeg)
![d53a87c4-d6fa-4e30-9d59-89cf13abf861](https://user-images.githubusercontent.com/45858543/49962660-1286fd00-ff16-11e8-985e-f66121a96c47.png)

**Comment by MarvinZeising** [comment]
Will do :-)
