### ISSUE TITLE
Kein Bericht

### ISSUE THREAD

**Issue by MarkusVa** [JWDeveloper/JWManagement#368]
Es fehlen auf einmal die fehlenden Schichtberichte bzw. sobald man auf einen Eintrag klickt, lädt es nur, aber der Button "Bericht" fehlt.

**Comment by MarvinZeising** [comment]
Okay, hört sich seltsam an.
Kannst du mir schreiben, um welches Projekt es sich handelt und welche Schicht du aufmachst und erwartest den Bericht Button zu sehen?

**Comment by MarkusVa** [comment]
Hallo,

 

bei Versammlung Mödling- Schicht Seegrotte

26.2, 9-11 Uhr.

Der Br. hats mir gezeigt und ich habe mich auf meinem Handy dann auch eingeloggt mit seinem Account und ich hatte kein Feld Bericht.

Dann habe ich eine Sr. ersucht nachzusehen, obs bei ihr auch so ist und sie meinte auch, dass auf einmal das Feld Bericht fehlt. 

Als Admin sehe ich aber alles.

 

Danke und LG,

Markus

 

Gesendet: Donnerstag, 28. Februar 2019 um 08:51 Uhr
Von: "Marvin Zeising" <notifications@github.com>
An: JWDeveloper/JWManagement <JWManagement@noreply.github.com>
Cc: MarkusVa <forza-viola@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [JWDeveloper/JWManagement] Kein Bericht (#368)


Okay, hört sich seltsam an.
Kannst du mir schreiben, um welches Projekt es sich handelt und welche Schicht du aufmachst und erwartest den Bericht Button zu sehen?

**Comment by MarvinZeising** [comment]
Die Schicht ist in der Zukunft. Den Bericht kann man erst ab dem Tag der Schicht eintragen.

**Comment by MarvinZeising** [comment]
Ach sorry, das ist natürlich quatsch. Ich schau es mir nachher mal genauer an.

**Comment by MarvinZeising** [comment]
In der genannte Schicht gibt es keinen Teamleiter. Nur ein Teamleiter (unterstrichen) kann den Bericht eintragen. Was mich zu der Frage bringt, wie das denn sein kann? Im Moment sollte das eigentlich nicht passieren können...
Wenn das mal nicht klappt, kannst du das als Administrator korrigieren indem du die Schicht aufmachst und bei dem vorgesehenen Teamleiter auf das Stern-Icon neben seinem Namen klickst.
