### ISSUE TITLE
Festlegung TL

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#37]
Muss die Festlegung, wer TL  in der Schicht ist manuell festgelegt werden, oder erfolgt das automatisch?
Davon ausgehend, dass schon min. ein TL sich in der Schicht angemeldet hat.

**Comment by MarvinZeising** [comment]
Das erfolgt automatisch.
Bei der "sofortigen Annahme" bei der letzten Bewerbung, die dazu führt, dass alle Bewerber angenommen werden.
Bei "manueller Annahme" mit Klick auf den "Ausgewählte annehmen" Button.
Die Entscheidung des Systems kann danach aber korrigiert werden, indem jemand anderes als Teamleiter eingeteilt wird.

**Comment by alisander2** [comment]
Beispiel bei uns 07.02..2017 12.00 - 14:00. Die Schicht ist jetzt mit vier VK belegt, davon 2 TL.
Aber als TL ist noch keiner markiert.

**Comment by MarvinZeising** [comment]
Tatsache... Schau ich mir an, danke.

**Comment by MarvinZeising** [comment]
Kann es sein, dass drei der vier VK schon vor dem Update (also vor dem 02.01.2017) in der Schicht waren, aber keiner von ihnen als Schichtleiter eingesetzt war?
Weil das System im Moment bei Nachbewerbern davon ausgeht, dass einer der bereits angenommenen VK schon als TL eingesetzt ist. Dementsprechend wird auch der Nachbewerber nicht als TL eingesetzt.

**Comment by alisander2** [comment]
Guten Morgen,
ja, dass könnte sein. Muss ich beobachten. Denke schon, dass es bereits so eingeteilt war und dann das Update kam. 
Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Mon, Jan 9, 2017 at 12:07 AM +0100, "Marvin Zeising" <notifications@github.com> wrote:












Kann es sein, dass drei der vier VK schon vor dem Update (also vor dem 02.01.2017) in der Schicht waren, aber keiner von ihnen als Schichtleiter eingesetzt war?

Weil das System im Moment bei Nachbewerbern davon ausgeht, dass einer der bereits angenommenen VK schon als TL eingesetzt ist. Dementsprechend wird auch der Nachbewerber nicht als TL eingesetzt.

**Comment by MarvinZeising** [comment]
Da der Fehler vorerst wohl nicht mehr aufgetreten ist, schließe ich die Issue mal.
Sollte er wieder auftreten, kann sie ja wieder geöffnet werden.
