### ISSUE TITLE
Einladungs-/Aktivierungsemail führt zu Abbruch bei vergebenem Benutzernamen

### ISSUE THREAD

**Issue by Marco010101** [JWDeveloper/JWManagement#370]
Hallo zusammen, 

wenn man eine Einladungsmail versendet und der Empfänger darüber einen neuen Account anlegen möchte kommt es oft zu der Fehlermeldung: Dieser Link ist ungültig, lass dir eine neue Email zusenden. Auch beim erstmaligen benutzen. 

Das passiert aber nicht immer. Ich konnte es reproduzieren, wenn ich einen bereits vergebenen Benutzernamen (in meinem Testbeispiel nutzte ich den Benutzernamen "Test" und "Tester") oder die Emailadresse als Benutzernamen gewählt hatte. Und ich vermute, dass es bei den VK auch so war.  

Da wir ab dem 16.03. ein Projekt mit 300 VK starten möchten würde ich mich über einen schnellen Workaround o.ä. sehr freuen... :-)

**To Reproduce**
1. Einladung versenden
2. neuen Account anlegen
3. einen bereits gewählten Benutzernamen verwenden (z.B. Tester), PW vergeben etc.
4. Error: Dieser Link ist ungültig, lass dir eine neue Email zusenden.
Benutzer kann sich nicht anmelden und muss solange eine neue Einladungsemail erhalten, bis er einen Unique Benutzernamen erwischt... 

--> Versende ich eine Einladungsemail und nutze eine garantiert Unique Name (z.B. Juhu9191) erscheint keine Fehlermeldung

Der Fehler tritt auf allen Endgeräten auf. 

**Expected behavior**
Fehlermeldung "Benutzername bereits vergeben" und die Möglichkeit einen neuen zu wählen statt den Abbruch.

**Comment by datascientistgonzo** [comment]
Habe dasselbe Problem ...

**Comment by MarvinZeising** [comment]
Das ist eine fantastische Fehlermeldung! Vielen Dank!
Ich habe mich schon seit längerem gefragt, warum da hin und wieder Probleme sind und keine Lösung gefunden. Besonders weil ich auch dachte das Benutzernamen-Problem schon gelöst zu haben...

**Comment by MarvinZeising** [comment]
Ich habe das mal nachgetestet und konnte es leider nicht mehr reproduzieren.
Lediglich wenn man eine E-Mail Addresse als Benutzername verwendet hat, trat dieser Fehler auf.
Das habe ich nun gelöst und man bekommt eine ordentlich Fehlermeldung wenn man eine E-Mail Adresse eingegeben hat. Und der Link bleibt weiterhin gültig.
Vielleicht war das ja auch in vielen Fällen der Fehler...

**Comment by datascientistgonzo** [comment]
Prima, vielen Dank!

**Comment by Marco010101** [comment]
Hi Marvin, 
danke, das freut das Product-Owner-Herz... :-)

Wir haben das Problem leider nach wie vor bei vielen VK. Ich habe daher den Workaround rausgegeben zuerst ein Benutzerkonto anzulegen (dort funktioniert die Fehlermeldung einwandfrei). Dann auf die Aktivierungsmail zu klicken und den Weg über "ich habe bereits ein Benutzerkonto" zu nutzen. 

Ich konnte das Problem nicht mehr mit jedem Benutzernamen nachstellen, aber folgender Weg führt bei mir nach wie vor zu dem Fehler:  
Einladungsemail - I need to create an Account
Benutzername: Test 
PW: testtest
= expired Link
Benutzername: Tester 
PW: testtest
= expired Link
Benutzername: mbier7 
PW: testtest
= korrekte Fehlermeldung = Benutzername existiert bereits

Wenn wir den Fehler gemeinsam reproduzieren sollen kannst dich gerne melden, dann machen wir mal ein GoTo zusammen... 

Grüßle
Marco

**Comment by MarvinZeising** [comment]
Jetzt hab ichs gefunden! Der username check war case sensitive. Deshalb ist ihm das erst beim Erstellen des Accounts auf dem Server aufgefallen und nicht schon beim check davor. Das habe ich jetzt geändert.
Danke dir, Marco!
