### ISSUE TITLE
passwort reset

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#38]
Das Zurücksetzen des Passwort geht nicht. 
das System findet meine email nicht....

**Comment by tim-antkowiak** [comment]
Da sind uns momentan keine Probleme bekannt.
Ich habe mal eine "Passwort zurücksetzen" E-Mail an deine hinterlegte E-Mail Adresse schicken lassen. Wahrscheinlich lag es daran, dass bei der Adresse Groß-/Kleinschreibung beachtet wird. Das werde ich demnächst aber noch ändern.

**Comment by kepano75** [comment]
Hallo Timstimmt ich kann es auch nicht mehr direkt nachstellen. Der Effekt war so, das die sich Datei nicht mehr öffnen ließ...Sollte ich es nochmal haben, dann lass ich die Datei drin und melde ein neues Ticket. 
lg Stephan 
Get Outlook for iOS




On Fri, Jan 6, 2017 at 2:20 PM +0100, "Tim Antkowiak" <notifications@github.com> wrote:












Closed #38 via 6164ac8.
