### ISSUE TITLE
Problem sich in Schichten anzumelden

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#40]
Hallo,

ich wurde schon von einigen VK angeschrieben, dass man sich für manche Schichten nicht bewerben kann.

Beispiel am 04.03.
Dort waren meine Frau und ich in einer Schicht eingetragen. Dann bekamen wir den Hinweis, dass man sich gern darauf bewerben würde. Die Möglichkeit bestand aber gar nicht. VK konnten sich nicht bewerben, obwohl die Schicht als offen angezeigt wurde. Ich konnte nur über das manuelle Hinzufügen VK in die Schicht nehmen.

**Comment by MarvinZeising** [comment]
Für den 04.03. habe ich keine Schichten in deinen Projekten gefunden.
Dementsprechend kann ich leider auch nicht sehen, wie die Schicht aussieht und warum Bewerbungen darauf nicht möglich waren. Habe leider auch sonst keine Idee, woran das liegen könnte...
Wenn das nochmal auftreten sollte, würde ich mich freuen davon zu erfahren.
Bis dahin schließe ich die Issue mal.

**Comment by alisander2** [comment]
Hallo,
die Schichten sind doch drin am 04.03.

Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Sun, Jan 8, 2017 at 8:54 PM +0100, "Marvin Zeising" <notifications@github.com> wrote:












Für den 04.03. habe ich keine Schichten in deinen Projekten gefunden.

Dementsprechend kann ich leider auch nicht sehen, wie die Schicht aussieht und warum Bewerbungen darauf nicht möglich waren. Habe leider auch sonst keine Idee, woran das liegen könnte...

Wenn das nochmal auftreten sollte, würde ich mich freuen davon zu erfahren.

Bis dahin schließe ich die Issue mal.

**Comment by MarvinZeising** [comment]
Oh ja stimmt, entschuldige bitte. Da habe ich wohl etwas durcheinander geschmissen.

Bei der Schicht ist das Team geschlossen (deshalb auch grau), was Bewerbungen verhindert.
Allerdings ist nicht die komplette Schicht geschlossen, was mich auf einen Bug schließen lässt.

**Comment by MarvinZeising** [comment]
Der Fix geht mit dem nächsten Release live

**Comment by alisander2** [comment]
Kein Problem!
Es war die Schicht, wo ich drin bin.Da war meine Frau und ich drin. Die anderen VK musste ich manuell hinzufügen. 
Zwei andere wollte sich anmelden, war nichtmöglich. 

Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Sun, Jan 8, 2017 at 10:07 PM +0100, "Marvin Zeising" <notifications@github.com> wrote:












Oh ja stimmt, entschuldige bitte. Da habe ich wohl etwas durcheinander geschmissen.


Bei der Schicht ist das Team geschlossen (deshalb auch grau), was Bewerbungen verhindert.

Allerdings ist nicht die komplette Schicht geschlossen, was mich auf einen Bug schließen lässt.
