### ISSUE TITLE
Profildaten

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#41]
Müssen nach dem Update alle VK ihre Profildaten wegen der kurzfristigen Verfügbarkeit bearbeiten?

Welche Auswirkungen haben diese Einstellungen überhaupt?

**Comment by MarvinZeising** [comment]
Diese Einstellungen sind eigentlich nur für das Popup interessant, mit dem Verkündiger manuell einer Schicht zugeteilt werden können.
Dort werden Verkündiger lediglich dann als verfügbar angezeigt, wenn die Schichtzeit:
- in die in der Verfügbarkeitstabelle angegebenen Zeiträume fällt
- nicht in einen ihrer Urlaubszeiträume fällt

Dies soll in Zukunft um die von dir angesprochenen kurzfristigen Verfügbarkeiten ergänzt werden.
Auf die Bedeutung von "kurzfristig" haben wir uns noch nicht geeinigt. Aber ich würde vorschlagen, dass es "den selben Tag, oder weniger als 24 Stunden vor der Schicht" bedeutet.
Die zweite Option "Auch wenn keine Verfügbarkeit angegeben ist" haben wir uns als Idee für z.B. Schicht-Arbeiter überlegt, die weniger Verfügbarkeit angeben würden, als sie eventuell tatsächlich haben. So wird den einteilenden Brüdern gezeigt, dass im Notfall (wenn kein anderer Verkündiger kurzfristig einspringen kann) auch diese Verkündiger gefragt werden können, ob ihre Schicht-Arbeit in dieser Woche eventuell so fällt, dass sie einspringen könnten.

Zusammenfassend müssen die Verkündiger ihre Einstellungen also nicht überarbeiten, wenn sie gar keine Verfügbarkeit angeben möchten.

Mit #33 möchten wir die Verfügbarkeitstabelle bei der Einteilung einblenden, damit der Einteiler schnell sieht, wie der Zeitplan des Verkündigers aussieht und an welchen Tag und Zeiten er in dieser Woche noch Bewerbungen hat.

**Comment by muhkuhxy** [comment]
Fragen scheinen mir umfassend beantwortet, ich schließe das issue mal.
