### ISSUE TITLE
After changing project permission - No User have the permission for project manager (administrator))

### ISSUE THREAD

**Issue by jonasrump** [JWDeveloper/JWManagement#422]
I have taken my project permission from "project manager" (administrator) to "shift scheduler". This was a mistake, now I can not add publishers, manage the website and so on.
Unfortunately, no other publisher has the permission "project manager" (administrator), and can give me the permission back.

Someone know a way to solve the problem?

**Comment by nikodemak** [comment]
contact @MarvinZeising using email or discord proveided on the site's support section

**Comment by mh166** [comment]
Well, the problem ist, that there seems to be no support page no more. At least I was unable to find it. But luckily, [in the code](https://github.com/JWDeveloper/JWManagement/blob/7504fe4454cb268caba2cacc5d84e298bede4833/imports/api/projects/service.js#L116-L119) it's still there. 😃

So as @nikodemak mentioned, you can use [Discord](https://discord.gg/Te9TKD8) or even phone the number mentioned in the code. Email support, unfortunately, doesn't seem to be available anymore.

**Comment by jonasrump** [comment]
Thanks for the answers.
Yes, the code ist still here. But I have no access to the database where I can change the permissions. Or what do you mean?
Thanks for the Idea with the phone number in the code. I will text him.

**Comment by MarvinZeising** [comment]
Permissions have been restored.
Thanks, guys.
