### ISSUE TITLE
More icons for teams

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWManagement#48]
Make it possible to define what icon is being used by a team.
This should be editable via the team section on the settings page.

I see two options for this:
1. Manually name the FontAwesome icon (e.g. "user" for fa-user).
2. Have like a dropdown with preselected choosable icons that the user just has to click on.

The specified icon then is shown in the shift and shiftModal templates.

**Comment by rnvrl** [comment]
Initial commit in 4916fd5753f7ebdce6df7ab9026bc115b154b12f
Using [fontIconPicker](https://github.com/micc83/fontIconPicker) as selector
