### ISSUE TITLE
Bild-upload, Browser spinnt bei falschem Fromat

### ISSUE THREAD

**Issue by Thomasks8** [JWDeveloper/JWManagement#6]
Hi,
in "Mein Profil" > "Bild Ändern" stürzt der Browser ab (zeigt nur noch unvollständige Seiten an, auch nach "Zurück"-Button anklicken), wenn man aus Versehen ein falsches Bildformat (bei mir .BMP) angeklickt hat. Da der Dateibrowser keine Dateiendungen anzeigt, kann es verwirrend sein, wenn man die Ursache dafür (falsches Anklicken) nicht bemerkt hat :-).
Der Fehler tritt sowohl beim IE als auch bei Chrome auf.
Des weiteren zeigt der Internet Explorer 11 bei mir das Verfügbarkeitsfenster nach den pers. Daten nicht an, sondern nur "Urlaub hinzufügen". Wäre schön, wenn das geht, da ich nur den IE am Laptop benutzen möchte :-).
Thomas

**Comment by MarvinZeising** [comment]
Wenn ich den Fehler richtig einschätze, bringt er den gesamten Server zum Absturz. Dadurch kann dein Browser keine neuen Daten mehr laden, was dann so aussieht, als ob der Browser abgestürzt wäre.

Ich habe mal die Funktion entfernt, die die Bilder vor dem Upload in PNGs umwandelt. Dadurch sollte kein Fehler mehr auftreten, wenn die Umwandlung nicht klappt.
Falsche Dateiformate sollten zu einer Fehlermeldung führen und gar nicht erst weiter verarbeitet werden.

Schließe die Issue vorerst mal.
