### ISSUE TITLE
Email an Alle / Mail to all

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#64]
Bitte die Mail Adresse in das BCC kopieren lassen

**Comment by MarvinZeising** [comment]
Daniel (@tinwhisker) already did this in the old repo. He may redo it here

**Comment by tinwhisker** [comment]
Yes, I'm changing it to use the mailer methods, rather than my old fix.

**Comment by MarvinZeising** [comment]
So you mean that the system automatically sends the mail?
Well then you'd also need to provide the possibility to set the subject and message. This would equal #56

**Comment by MarvinZeising** [comment]
The fix will go live with the next release
