### ISSUE TITLE
Bewerbung Zurückziehen nach dem ein Team geschlossen wurde

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#66]
Nachdem ein Team geschlossen wurde, sollte ein Zurückziehen nur angezeigt werden, ggf. Mit Begründung. Nur der Schichtleiter darf endgültig den Verkündiger aus der Schicht löschen, z.B. wenn er einen Ersatz gefunden hat.

**Comment by MarvinZeising** [comment]
Wenn wir #21 auch auf normale Teilnehmer erweitern, sollte der Sinn hiervon im Kern abgedeckt sein.
