### ISSUE TITLE
Keine Teilnehmer hinzufügbar 

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#68]
Nur im Projekt Saalkomplex-Neukölln lässt sich kein Teilnehmer mehr hinzufügen... ging aber schon mal...
In meinem anderen Projekt geht es!

**Comment by kepano75** [comment]
Also Verkündiger zu einer Schicht hinzufügen...

**Comment by MarvinZeising** [comment]
Wurde mit [1115b49](https://github.com/JWDeveloper/JWManagement/commit/1115b497a5a1579c5ae48ebd1ef97164f61001a7) gefixt
