### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by ream88** [JWDeveloper/JWManagement#7]
I failed on trying to install it locally ;)

**Comment by MarvinZeising** [comment]
Yeah install instructions are coming in the future.

Also forgot a file for the meteor initialization.
Added that in [4041655](https://github.com/JWDeveloper/JWManagement/commit/40416552cbe5e08e5b3b59f640746c5495b54ef6)

If you have installed meteor, just run "meteor" from the command line in the cloned folder

**Comment by MarvinZeising** [comment]
What do you think? Do these instructions help you?

**Comment by MarvinZeising** [comment]
Closing this since the problem seems to be fixed
