### ISSUE TITLE
Schichtbericht 

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#76]
Ältere Schichtberichte lassen sich nicht editieren und werden als "fehlender" schichtbericht angezeigt.

![fehler](https://cloud.githubusercontent.com/assets/24876980/21804920/bd64e53e-d731-11e6-8f64-0869fe0f3000.JPG)

**Comment by MarvinZeising** [comment]
Der Fix geht mit Release 1.06 live
