### ISSUE TITLE
Schichthinweis bei Absage der Schicht

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#80]
Wegen des Unwetters haben wir für morgen die Schichten abgesagt über die Funktion, "Team absagen"!
Die Email enthält für die VK aber keinen Hinweis auf das Datum, welche Schicht abgesagt wird. Habe zwar nen Hinweis geschrieben warum, aber nicht auf das Datum.

Da fehlt leider ein automatisches Datum.

**Comment by tim-antkowiak** [comment]
Entschuldige, da habe ich den falschen Textblock in die Mail eingefügt.
Die Verbesserung geht mit dem nächsten Release online.

**Comment by alisander2** [comment]
Kein Thema!
Wisst ihr, wann das Release kommt?

Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Fri, Jan 13, 2017 at 5:58 PM +0100, "Tim Antkowiak" <notifications@github.com> wrote:












Entschuldige, da habe ich den falschen Textblock in die Mail eingefügt.

Die Verbesserung geht mit dem nächsten Release online.

**Comment by tim-antkowiak** [comment]
Spätestens morgen früh sollte das online sein.

**Comment by alisander2** [comment]
Wow!

Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Fri, Jan 13, 2017 at 6:33 PM +0100, "Tim Antkowiak" <notifications@github.com> wrote:












Spätestens morgen früh sollte das online sein.
