### ISSUE TITLE
Zukünftige Schichten werden erst unter Ältere angezeigt 

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#81]
Ältere Schichten via Drop-down Menü ist gut...
Zukünftige Schichten sollten aber nicht unter ältere zu finden sein...

**Comment by tim-antkowiak** [comment]
Danke für den Hinweis!

**Comment by MarvinZeising** [comment]
Ich habe das Problem anders verstanden. So, dass nach dem Klick auf "Ältere zeigen" keine kommenden Schichten mehr gezeigt werden sollten. Das ist aber nicht die Absicht des Buttons.
Deshalb benenne ich den mal um.

**Comment by MarvinZeising** [comment]
Die Änderungen gehen mit dem nächsten Release live.

Ist das Problem damit gelöst?
