### ISSUE TITLE
Alle Schichten Anzeigen 

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#82]
In der Kachel-Ansicht der Schichten, bitte eine Kachel mit "Alle anzeigen" einrichten, die immer als erstes Kachel angezeigt wird.
So kann man direkt alle Schichten parallel sehen, ohne noch weitere Augen-Funktionen zu bedienen

**Comment by MarvinZeising** [comment]
Button wurde mit f6fe601 eingebaut und wird mit dem nächsten Release live gehen.
