### ISSUE TITLE
Absage von Schichten - Fehler?

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#87]
Hallo, ich habe wegen des Wetters einige Schichten letzte Woche absagen müssen.
Wie ich jetzt erfahren habe, haben nicht alle die Email erhalten.
Speziell weiß ich von einem Fall, dass er  in eine Schicht erst später rein kam. Diese war schon einmal geschlossen. ich habe sie dann manuell geöffnet und dann hat er sich eingetragen. Dieser Bruder (selbst Programmierer) hat dann keine Email erhalten. Wir haben es nachgeprüft und es war so.

**Comment by tim-antkowiak** [comment]
Zugeteilte Verkündiger erhalten nur Absage- und Änderungs-E-Mails, wenn sie auch über ihre Zuteilung per E-Mail informiert wurden (entweder über den Button "Zuteilungen senden" oder einzeln über den Papierflieger in der Zeile des Verkündigers). Ob ein Teilnehmer über seine Zuteilung informiert wurde, erkannt man an dem Papierflieger ganz rechts in der Zeile des Teilnehmers. Ist dieser blau ausgefüllt, wurde der Verkündiger informiert.

**Comment by MarvinZeising** [comment]
Außerdem werden keine E-Mails geschickt, wenn die Person die Information noch nicht gesehen hat. Da der Bruder hier schon beim Eintragen in die Schicht gesehen hat, dass er angenommen wurde, verschickt das System keine Mail mehr - frei nach dem Motto "Warum jemanden über etwas informieren, was er schon weiß"

Davon mal abgesehen ist das hier schon uralt. Ich schließe es daher mal
