### ISSUE TITLE
keine "sofortige Zusage"

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#88]
Siehe 23.01.2017
Obwohl die Schicht auf sofort annehmen steht und ein TL drin ist, kann sich ein vierter VK nicht anmelden , bleibt in "gelb" stehen. Auch ich kann den VK nicht manuell annehmen, weil angeblich ein TL fehlt. Der ist aber drin

**Comment by tim-antkowiak** [comment]
Um welche Schicht an dem Tag geht es genau? Mir ist da bis jetzt noch kein Fehler aufgefallen.

**Comment by alisander2** [comment]
Das war die um 8:00-10:00Jetzt ist da leider auch der TL raus, da kann man es nicht mehr sehen. Schade.
Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Tue, Jan 17, 2017 at 9:20 PM +0100, "Tim Antkowiak" <notifications@github.com> wrote:












Um welche Schicht an dem Tag geht es genau? Mir ist da bis jetzt noch kein Fehler aufgefallen.

**Comment by alisander2** [comment]
gleicher Fehler siehe 09.02. 08:00-10:00.
Dort ist ein TL drin, aber es ist nicht geschlossen und nichts angenommen.

**Comment by tim-antkowiak** [comment]
Okay, hab es gesehen. 
Das liegt an einem Bug in der automatischen Zuteilung wenn sich der Teamleiter als letztes bewirbt. Ich schau mal dass ich das heute Abend verbessert bekomme.

Die manuelle Zuteilung sollte aber funktionieren.
