### ISSUE TITLE
Dateien mit Umlauten öffnen sich nicht

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#9]
getestet mit ü
Nach upload lässt sich die Dstei nicht öffnen

**Comment by tim-antkowiak** [comment]
Hallo kepano75,
ich kann den Bug leider nicht reproduzieren. Wenn die Datei größer als 0 Byte ist, sollte man sie auch herunterladen können.

Welchen Browser benutzt du?

**Comment by MarvinZeising** [comment]
Von Stephan (@kepano75):
> Hallo Timstimmt ich kann es auch nicht mehr direkt nachstellen. Der Effekt war so, das die sich Datei nicht mehr öffnen ließ...Sollte ich es nochmal haben, dann lass ich die Datei drin und melde ein neues Ticket. 
lg Stephan

_(moved to this thread)_
