### ISSUE TITLE
Ändern der Profildaten durch den Admin

### ISSUE THREAD

**Issue by kepano75** [JWDeveloper/JWManagement#90]
Da ich gerade ein Projekt anlege mit zunehmenden Verkündiger habe ich den Import mit csv genutzt. 
Es gab jedoch hier und dort einige Schreibfehler und musste Namen und email Adresse ändern. 
Es gibt auch einige Namen die ich Importieren möchte, bei denen mir noch die Mail Adresse fehlt. 

Leider kann ich nicht mehr die Profile manuell als Admin ändern. Früher konnte ich einem Verkündiger sogar ein Start Passwort vergeben. 

Bitte die Möglichkeit der Änderung des Profils, durch den Admin ermöglichen.... Danke

**Comment by kepano75** [comment]
Gibt es hier Fortschritte? Ich müsste hier bei einigen die Daten ändern. Wegen Zusammenlegung von Versammlungen und weiteres.  
- Versammlungsname
- Vorechte
- Vor und Nachname
- Benutzername falls falsch eingegeben

**Comment by MarvinZeising** [comment]
Lässt sich mittlerweile auf [staging.jwmanagement.org](staging.jwmanagement.org) machen. Wird dann bald auch nach www.jwmanagement.org deployed.
