### ISSUE TITLE
Fehler -Anlegen von neune Wochen bei unterschiedlichen Tags!

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#92]
Hallo,
ich habe eben für einen TAG (Kassel Nordwest) eine Schicht in der Woche vom 30.01.-05.03. angelegt.

Dabei habe ich aus versehen wohl unten als Schichtvorlage Kassel Innenstadt ausgewählt. Das System hat nichts angelegt, als ich dann es mit der Vorlage Kassel Nordwest probiert habe, hat es geklappt.

ABER meine komplette Schicht Woche im TAG Kassel Innenstadt in der Woche ist jetzt weg!!
Das sollte schnell behoben werden und bei der Auswahl der Schichtvorlage sollte die Vorlage drin stehen, von dem TAG in dem ich mich befinde.

**Comment by alisander2** [comment]
Wenn ihr in den TAG "Kassel Innenstadt" schaut, in der Woche am 20.02., da seht ihr ein weiteres Ergebnis des Fehlers.
wir haben die Wochen eigentlich versucht im TAG "Kassel Nordwest" anzulegen, haben aber die falsche Vorlagewoche ausgewählt. 
Ist es möglich, dass man bestimmt, welche Vorlagewoche in einem TAG verfügbar ist?
Auch sollte die dann nicht in einem anderen TAG ausgeführt werden.

**Comment by MarvinZeising** [comment]
Habe mal nachgeschaut und in der Funktion zum Anlegen von neuen Wochen ist nirgendwo Code zum Löschen von Schichten drin. Die einzige logische Erklärung für den Fehler ist für mich im Moment nur, dass jemand aus Versehen in der falschen Woche alle Tage gelöscht hat.

Was meinst du mit bestimmen, welche Vorlagewoche in einem Tag verfügbar ist?
Im Moment ist es so, dass du selbst bestimmst, welche Vorlagewochen es in welchen Tags gibt.
Deine heißen ja nur zufällig beide Standard, obwohl es unterschiedliche Vorlagen in verschiedenen Tags sind. Oder habe ich die Frage missverstanden?

**Comment by alisander2** [comment]
Ja, die eine Vorlagewoche heißt Innenstadt und die andere Kassel Nordwest. 
Es hat wahrscheinlich nichts gelöscht, aber überschrieben. 
Es war auch kein anderer! Ich habe ausschließlich Wochen für Nordwest anlegen wollen und es wurde bei der Vorlagewoche  in der Dropdown-Menü "Innenstadt" ausgewählt   Das wollte ich gar nicht, aber es hat dann nicht im TAG Nordwest angelegt, ist nichts passiert. Aber im TAG Innenstadt. Da war die Wochen die ich dir geschrieben habe betroffen. 


Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Sat, Jan 28, 2017 at 3:48 AM +0100, "Marvin Zeising" <notifications@github.com> wrote:












Habe mal nachgeschaut und in der Funktion zum Anlegen von neuen Wochen ist nirgendwo Code zum Löschen von Schichten drin. Die einzige logische Erklärung für den Fehler ist für mich im Moment nur, dass jemand aus Versehen in der falschen Woche alle Tage gelöscht hat.


Was meinst du mit bestimmen, welche Vorlagewoche in einem Tag verfügbar ist?

Im Moment ist es so, dass du selbst bestimmst, welche Vorlagewochen es in welchen Tags gibt.

Deine heißen ja nur zufällig beide Standard, obwohl es unterschiedliche Vorlagen in verschiedenen Tags sind. Oder habe ich die Frage missverstanden?

**Comment by MarvinZeising** [comment]
Nein, deine Vorlagewochen heißen beide "Standard". Lediglich die Tags heißen "Kassel Innenstadt" und "Kassel Nordwest".
Ich habe das genau so probiert, wie du es gesagt hast und es geht. Ich habe eine bestehende Woche mit Einteilungen genommen und die selbe Vorlage noch einmal darauf angewendet. Dadurch sind neue Schichten hinzugekommen, aber keine weggefallen.
Natürlich glaube ich dir, immerhin habe ich das Ergebnis ja mit eigenen Augen gesehen. Um den Fehler zu finden, muss ich das Problem allerdings nachstellen können und das kann ich in diesem Fall nicht.

**Comment by alisander2** [comment]
Müssen mal telefonieren, wollte dir eine Email mit Bildern senden. Die ist aber zu groß und kommt nicht an. 
LG, Alexander

Mit freundlichen Grüßen 
Alexander Mund 

Harleshäuser Str. 124 A 
34128 Kassel 
Tel (0561) 870 47 40 
Fax (0561) 870 47 41 
________________________________________ 
Mund Pflegedienst GmbH . Harleshäuser Str. 124 A . 34128 Kassel 
Handelsregister: Amtsgericht Kassel - HRB 17137 . Eingetragen im Handelsregister B . Sitz der Gesellschaft ist Kassel Geschäftsführender Gesellschafter: Liane Mund 
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Sat, Jan 28, 2017 at 1:38 PM +0100, "Marvin Zeising" <notifications@github.com> wrote:












Nein, deine Vorlagewochen heißen beide "Standard". Lediglich die Tags heißen "Kassel Innenstadt" und "Kassel Nordwest".

Ich habe das genau so probiert, wie du es gesagt hast und es geht. Ich habe eine bestehende Woche mit Einteilungen genommen und die selbe Vorlage noch einmal darauf angewendet. Dadurch sind neue Schichten hinzugekommen, aber keine weggefallen.

Natürlich glaube ich dir, immerhin habe ich das Ergebnis ja mit eigenen Augen gesehen. Um den Fehler zu finden, muss ich das Problem allerdings nachstellen können und das kann ich in diesem Fall nicht.

**Comment by alisander2** [comment]
Ich habe es gerade probiert und ich kann den Fehler reproduzieren.

Geh mal in den TAG Kassel Nordwest
Leg dann mal eine neue Woche an, ideal die Woche vom 06.03.2017. Da ist noch nichts angelegt.
Dann Vorlagewoche nehmen die dort steht, müsste Innen Stadt - Standard sein. Wenn du dann auf anlegen klickst, dann zuckt der Bildschirm und es sieht aus, als ob er jetzt diese Schichten in dem TAG anlegt. sie sind aber dann im TAG Innenstadt.
Was ich nicht nachstellen konnte, dass er vorhandene löscht, sondern er hängt es immer noch zusätzlich dran.

**Comment by alisander2** [comment]
der Fehler kommt immer noch vor!

**Comment by MarvinZeising** [comment]
Ha! Seltsam, dass ich den Fehler nie bemerkt habe. Wobei das auch ein ganz kleiner, schwer zu findender Fehler war. Hab ihn letztens durch Zufall gefunden und gefixt. Kommt dann im nächsten Update (https://staging.jwmanagement.org).
