### ISSUE TITLE
Verkündiger manuell hinzufügen- Fehler

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#94]
Hallo, ich habe versucht am 31. 01. eine VK in  die Schicht manuell einzufügenden. Auch nach mehreren Versuchen hat es nicht geklappt. 
Es kommt die Maske von der Schicht, aber sie ist nicht drin.

**Comment by alisander2** [comment]
Ergänzung. Am Desktop geht es, am Ipad nicht!

**Comment by MarvinZeising** [comment]
Wenn ich mich nicht irre, sollte das den Fehler beheben. Sollte das nochmal vorkommen, kannst du die Issue ja wieder öffnen.
Der Fix geht mit dem nächsten Release live.
