### ISSUE TITLE
TL wird nicht automatisch festgelegt

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#96]
Hallo, als Beispiel 08.03. 08:00-10:00.
Ist es nicht so, dass wenn die Einstellung auf "sofort zusagen" steht und ein TL in der Schicht ist, er dann auch die Funktion hat? Oder muss ich es trotzdem manuell steuern, wer Teamleiter ist?

**Comment by MarvinZeising** [comment]
Nein, eigentlich sollte das automatisch gehen. Ich werde mal schauen, woran das liegt. Vielen Dank!

**Comment by MarvinZeising** [comment]
Sehe gerade, dass das mit #93 schon gelöst sein müsste. Geht mit dem nächsten Release live.
