### ISSUE TITLE
Wunsch - "Email an alle" TAG weise

### ISSUE THREAD

**Issue by alisander2** [JWDeveloper/JWManagement#97]
Es wäre klasse, wenn ihr die Funktion "Email an alle" um die Funktion erweitern könnten, dass man nur VK anschreibt, die eine Berechtigung in einem TAG haben.

zB ich möchte alle VK "Innenstadt" anschreiben, ohne das die VK des TAG "Nordwest" eine Email erhalten.

Das betrifft ja auch die Funktion, "Unterbesetzt Mail schicken". Da werden ja auch die angeschrieben, die gar keine Berechtigung haben

Das wäre super.
Gerade weil wir das System auch für zwei Erweiterungen in Kassel verwenden möchten.
Bibelausstellung und Sprachkurse oder Pio-Schulen. Das erleichtert die Planung für die Brüder!

Danke!

**Comment by MarvinZeising** [comment]
Super Gedanke, vielen Dank!

**Comment by alexlaux** [comment]
Oh ja auf diese Funktion warten wir auch, da wir mit 2 Versammlungen mit unterschiedlichen Tags arbeiten

**Comment by MarvinZeising** [comment]
Beide Änderungen wurden mit der Version 1.0.12 aufgespielt.
